### PR TITLE
ContikiMac: Make it more configurable (Sub-GHz)

### PR DESCRIPTION
**Pull request by uknoblic**
After having tested ContikiMac with the cc1200 driver (50kbps), we found out that we have to be able to modify some of the ContikiMac default settings. This PR adds the necessary modifications.

### CODE REVIEW

**Comment by alignan** [comment]
Cool! I have done the exact changes myself.  Please separate the `.gitignore` commit from the PR, and I'm ready to merge.

**Comment by vsaw** [comment]
The Java file seems to be a result of https://github.com/contiki-os/contiki/pull/1318. Can you try to update the PR to exclude it?

Other than that it seems to be straightforward and useful!

**Comment by uknoblic** [comment]
To silly to clean-up this commit. Please help!

**Comment by vsaw** [comment]
Try the following:

```
git reset HEAD^
git add core/net/mac/contikimac/contikimac.c
git commit
git push -f
```

This should commit only the contikimac changes.

**Comment by simonduq** [comment]
I wouldn't date `git push -f` without explicit remote and branch!

**Pull request closed without merging**
