### PR TITLE
Zolertia Z1: Direct memory access using UART.

### PR DESCRIPTION
**Pull request by sumanpanchal**

### CODE REVIEW

**Comment by simonduq** [comment]
Great! From offline discussions with @sumanpanchal I know this improves serial reliability significantly, especially on a BR running TSCH (frequent interrupts).

I wonder if this shouldn't be disabled by default at first, so that people can try it without affecting others. Also, I know this was tested on H/W, but does mspsim also support DMA on f2xxx? If not, that's an extra reason to disable by default.

**Comment by alignan** [comment]
@simonduq agree, this should be optional, happy to merge if so.
@sumanpanchal thanks for the contribution!

**Comment by sumanpanchal** [comment]
@simonduq @alignan  Thanks for the feedback. 
As mspsim doesnt have DMA support on f2xxx. I have disabled the DMA for Z1 mote as per your suggestion.

**Comment by simonduq** [comment]
:+1:

**Comment by sumanpanchal** [comment]
@alignan Code style fixed as per your suggestion.

**Comment by alignan** [comment]
:+1:

**Pull request merged**
