### PR TITLE
Driver for Plantower PMS 5003 dust sensors.

### PR DESCRIPTION
**Pull request by posjodin**
Platform-specific files for avr-rss2.

### CODE REVIEW

**Comment by herjulf** [comment]
And after reading up about different air-quality projects I see the Plantower PMSX003 dust sensors are getting widely used. So having a driver is an advantage. The driver should work for most models.

**Comment by herjulf** [comment]
You have not added the latest update of the duty cycling patches?

And the review of the PMS5003 sensor seems very interesting. So driver comes in handy...

**Comment by posjodin** [comment]
I made an update with revised logic for duty cycling with runtime-configurable timers. It also adds support for reading dust size counters for sensors that have that (PMS5003, at least).

**Comment by posjodin** [comment]
It seems that a Travis check fails with a Java error in Cooja. Not much I can do about that I guess.

**Comment by posjodin** [comment]
Rebased and resubmitted as PR #2347.

**Pull request closed without merging**
