### PR TITLE
Addet ECC functions on elliptic curve secp256r1.

### PR DESCRIPTION
**Pull request by SmallLars**
Rebase done, see pull request #624

### CODE REVIEW

**Comment by simonduq** [comment]
If you're still supporting this PR, please make sure Travis passes. @malvira can you check this PR?
If no activity I'll close in one month.
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by malvira** [comment]
this failed test seems legit: https://travis-ci.org/contiki-os/contiki/jobs/38699287

Can this be addressed?

The other one seems unrelated.

**Comment by SmallLars** [comment]
Since I did the pull request Contiki growed alot.
I reduced the amount of testvectors from 200 to 32
so the test can fit on econotag again.

**Comment by malvira** [comment]
Thanks for fixing the tests. Can you rebase? = and then we'll merge.

**Comment by SmallLars** [comment]
OK, rebase done. My friend worked with elliptic curves in his bachelor thesis.
I think we will do an update in the next weeks to improve speed and time constance
using projective coordinates. In a first test we reduced time of multiplication from
4,8 seconds to 3,3.

Maybe you can look to PR 618 to? Would be nice to hear your meaning about the AES interface.

**Comment by SmallLars** [comment]
Switch to projective coordinates is done faster as we expected. Because of time constance the execution time went up to 4,3 seconds, but its still 0,5 seconds faster as before. We was also able to reduce the program size.

**Comment by simonduq** [comment]
this is active again, removing timed out label

**Pull request merged**
