### PR TITLE
DINAS

### PR DESCRIPTION
**Pull request by ardarico**
Hi, I am Michele Amoretti from the University of Parma, Italy (http://www.ce.unipr.it/people/amoretti). The code I would like to contribute to Contiki is the result of the collaboration with the Drakkar Group at LIG Lab, Grenoble, France (http://drakkar.imag.fr/?lang=en), which started in 2013 and is still ongoing.

The code implements DINAS, a distributed naming service. Its description is available in the following paper: 
M. Amoretti, O. Alphand, G. Ferrari, F. Rousseau, A. Duda
DINAS: a DIstributed NAming Service for All-IP Wireless Sensor Networks
IEEE Wireless Communications and Networking Conference (WCNC), Istanbul, Turkey, April 2014. 

The current version of the code is updated with respect to the one used for the aforementioned paper (an extended DINAS paper based on this latest code is under review for the IEEE IoT Journal).

In this pull request, I provide 3 folders:
- apps/bloom-filter/ contains an implementation of the Bloom filter, based on Contiki's implementation of CRC16;
- apps/dinas/ contains the implementation of DINAS (note: rpl-updown is a particular overlay routing strategy based on RPL; in the future, I plan to implement other strategies, not necessarily based on RPL);
- examples/ipv6/rpl-dinas/ contains demo code (demo-dinas is the demo of DINAS; demo-centralized is the demo of a centralized naming scheme we used to compare with DINAS).

Best regards
Michele Amoretti

### CODE REVIEW

**Comment by simonduq** [comment]
I wonder what happened to the Travis test, but regardless, please check the wiki page on code contributions https://github.com/contiki-os/contiki/wiki/Code-Contributions

DINAS seems interesting but non-standard protocols that are the result of research projects usually go to http://sourceforge.net/projects/contikiprojects/ instead (unless a large part of the community shows interest AND there is a plan to keep the code maintained).

Please also note the code style needs fixing to comply with Contiki.

**Comment by ardarico** [comment]
Hi Simon, thank you for the reply. 

Probably it would have been better to separate the pull request into two parts:
- Bloom filter (which is general-purpose)
- DINAS

Can you be more specific about the fixes to the code style?

**Comment by simonduq** [comment]
Yes, more specific link here:
https://github.com/contiki-os/contiki/wiki/Code-Contributions#code-formatting

**Comment by nvt** [comment]
I agree with @simonduq that this is probably more suitable for the Contiki Projects repository. In addition to the code style issues, the bloom filter would fit more naturally as a library module instead of as an app. 

My proposal is that we close this PR, and invite you @ardarico to contact either me or Simon if you wish to have this work put into Contiki Projects.

**Comment by ardarico** [comment]
Hi, I agree with your comments. Thank for the feedback. I will contact either you or Simon asap. 
Feel free to close the PR.

**Pull request closed without merging**
