### PR TITLE
CCITT_CRC.java Change line endings from CRLF to LF

### PR DESCRIPTION
**Pull request by tsparber**
This is a whitespace change only. Similar to #756.
A problem with this file is also mentioned in a comment in #1162

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Ditto, I had an big issue with this particular file myself. Could you also remove some trailing whitespaces?

**Comment by tsparber** [comment]
Yes, sure. I just amended the commit.

**Comment by simonduq** [comment]
:+1:

**Comment by nvt** [comment]
:+1:

**Pull request merged**
