### PR TITLE
Add regression-test for tools

### PR DESCRIPTION
**Pull request by cmorty**
Currently fails due to unmerged https://github.com/contiki-os/contiki/pull/1048

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Hi Morty.

Is this meant for consideration or is it in progress?

**Comment by cmorty** [comment]
It's for consideration. I wasn't willing to fix all the bugs, but at least the working stuff will not break in the future. ;)

**Comment by g-oikonomou** [comment]
Reason I asked: I cannot see any changes to .travis.yml ;)

Sensinode nano_[usb_]_programmer can be ignored. Not even sure why I've left them there for that long...

**Comment by cmorty** [comment]
Ah, yes. My fault..... Was one of those: While I'm at it, I could quickly also.... - things. Should have taken more care. :/

**Comment by g-oikonomou** [comment]
@cmorty so now that I have a proper keyboard in front of me, I can say that this is a welcome feature!

**Comment by cmorty** [comment]
Ok, fails as expected due to #1048

**Comment by simonduq** [comment]
Excellent addition, :+1: as soon as Travis gets green (i.e. https://github.com/contiki-os/contiki/pull/1048 merged and this one rebased)

**Comment by simonduq** [comment]
https://github.com/contiki-os/contiki/pull/1048 now merged, can you rebase @cmorty?

**Comment by cmorty** [comment]
@simonduq There you go. :)

**Comment by simonduq** [comment]
Great! One question: what is the reason for the modified binaries? (`nano_programmer` and `serialdump-linux`)

**Comment by simonduq** [comment]
Perhaps related to https://github.com/contiki-os/contiki/issues/1073?

**Comment by cmorty** [comment]
@simonduq, binries: Did too much rebasing on too many branches and they accidentally slipped in.

**Comment by simonduq** [comment]
Great, thanks!

**Pull request merged**
