### PR TITLE
ND6 alignment bugfix

### PR DESCRIPTION
**Pull request by simonduq**
This PR ensures the second parameter of `uip_ds6_nbr_add` is word-aligned, which is required as the parameter is directly accessed as `uip_lladdr_t*` (not as a byte array).

Bug report from Deepak Sudhakar

### CODE REVIEW

**Comment by laurentderu** [comment]
:+1: 

I found a similar issue in ns_input() when UIP_LLH_LEN is != 0 :

<pre>
uip_ipaddr_copy(&UIP_IP_BUF->srcipaddr, &UIP_ND6_NS_BUF->tgtipaddr);
</pre>

makes a hardware fault on CC2538. I'll make a similar patch.

**Comment by nvt** [comment]
Maybe we could have a macro or a static function that does the copy here, and move the repeated comment to the definition of that macro or function.

**Comment by simonduq** [comment]
Looking closer at the code, I found this https://github.com/contiki-os/contiki/issues/1277

An added function or macro might create confusion: it would copy the address to a struct lladdr, which is needed only in particular cases (here, because it is used as parameter to function expecting a `uip_lladdr_t *`). There are many places in the file where the lladdr is accessed directly e.g. for a `memcmp`, and the reader might wonder why we sometimes do direct access, sometimes do a copy. So it will be hard to eliminate the duplicate comments.

**Comment by nvt** [comment]
I thought that the naming of the macro (e.g., to extract_lladdr_aligned()) would help to improve the understanding, but the current solution is also OK for me.

**Comment by simonduq** [comment]
Point taken, I'll try that!

**Comment by simonduq** [comment]
done :)

**Comment by nvt** [comment]
:+1:

**Pull request merged**
