### PR TITLE
Fix uip-ds.h tables configuration comment

### PR DESCRIPTION
**Pull request by MohamedSeliem**
this PR to update uip-ds.h comments, this small change is made to ease the track of Tables implementation places

### CODE REVIEW

**Comment by nvt** [comment]
Unfortunately, I do not find this change acceptable in its current state; the new text is not written properly.

**Comment by MohamedSeliem** [comment]
So, what are the kind of changes do you suggest to be written properly.

**Comment by nvt** [comment]
If you keep the original text, you can simply add a line in the end of the block comment saying that "The routing table definitions can be found in uip-ds6-route.h".

**Comment by MohamedSeliem** [comment]
Done.

**Comment by MohamedSeliem** [comment]
@nvt  any progress here ?

**Comment by simonduq** [comment]
no need for two commits here, could you please squash them?

**Comment by simonduq** [comment]
now replaced with https://github.com/contiki-os/contiki/pull/1849

**Pull request closed without merging**
