### PR TITLE
Assert that the ringbuf has the right size / Add compile time assert

### PR DESCRIPTION
**Pull request by cmorty**
This PR has to patches. The fist supports compile time asserts. The error itself is not really helpful, but as one still gets file name and line number its better than nothing.
The second uses the new compile-time assert-feature to ensure the the puffer passed the the ringbuf function fulfills the requirements.

### CODE REVIEW

**Comment by simonduq** [comment]
I agree with @nvt that the macro on top of the init function makes the code more complex than it needs to. I would close this PR. Will give it another month in case someone wants to save it.
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by cmorty** [comment]
@simonduq Still didn't get any feedback from @nvt on 8634e7a

**Comment by nvt** [comment]
I have a lukewarm feeling about this PR -- either merging or not merging is OK with me, but there are no clear supporters at the moment.

**Comment by cmorty** [comment]
@nvt, @simonduq: I still think it's at least a nice example of best coding practice, as it's the only way of making decent compile time assertions in C - even adding a message. Doing so in runtime code IMO is not reasonable, because they add unnecessary overhead that nobody checks anyway. 
However, as learning a bit about C was my main gain out of this, I can sleep well if it is not merged.

**Comment by simonduq** [comment]
not strong supporter, closing

**Pull request closed without merging**
