### PR TITLE
Fix serialdump.c

### PR DESCRIPTION
**Pull request by cmorty**
_GNU_SOURCE is needed for O_DIRECT
time.h is needed for strftime

### CODE REVIEW

**Comment by cmorty** [comment]
Please don't merge yet. There is a patch to come.

**Comment by msloth** [comment]
May I propose to make 115200 default instead of 57600 while you're at it? 115200 seems to be the de facto standard for most platforms.

**Comment by cmorty** [comment]
@msloth There you go. :)

**Comment by nvt** [comment]
Good to have a clean up of serialdump, but on a first look I noticed that the PR adds a space after some of the <code>for</code> and <code>switch</code> keywords.

**Comment by simonduq** [comment]
Very welcome fix and cleanup, and it seems @nvt's comment is addressed, so :+1: from me

**Comment by alignan** [comment]
:+1: as well, one less argument to my aliases :-)

**Pull request merged**
