### PR TITLE
Adding decryption function and example.

### PR DESCRIPTION
**Pull request by rfuentess**
An updated to the  implementation of AES-128 by software.  The decryption  its added together a example scenario (based in the example/ipv6/simple-udp-rpl.

### CODE REVIEW

**Comment by rfuentess** [comment]
Ok.  I think the  issues with the write access    has been fixed.

**Comment by cmorty** [comment]
There is some code cleanup to do to get through Travis, but from what I see that's rather easy.

**Comment by rfuentess** [comment]
Hi @cmorty , for the cleanup, there is another reference plus the  doc/code-style ?

**Comment by cmorty** [comment]
Oh, documentation is fine, it's just a bit buggy: see https://travis-ci.org/contiki-os/contiki/jobs/70754742
Removing the min-definition should fix https://travis-ci.org/contiki-os/contiki/jobs/70754759 and https://travis-ci.org/contiki-os/contiki/jobs/70754761
The wiki has documentation on how to update a PR.

**Comment by simonduq** [comment]
Many issues in this PR:
* modifies things it doesn't need to, e.g `sbox` in `aes-128.c`
* does more than the PR claims: in addition to new examples, `aes-128` is modified
* the code style is off, see https://github.com/contiki-os/contiki/wiki/Code-Contributions#code-formatting
* it is very unclear to me why the aes test needs to be ipv6-based, as this is bare aes testing, not llsec, I don't understand the need for networking

Will close this PR unless the author comes up with compelling arguments why this is still relevant.

**Comment by simonduq** [comment]
closing after timeout

**Pull request closed without merging**
