### PR TITLE
Added the OpenMote platform and examples

### PR DESCRIPTION
**Pull request by peretuset**
I have copied the CC2538DK platform and examples and adapted it to the OpenMote platform, which is also based on the CC2538 SoC. The code compiles fine and I am able to upload it and run it on the target platform. Comments in the source code will need to be ammended to match the target platform, but this can be done in the future.

### CODE REVIEW

**Comment by adamdunkels** [comment]
This one seems to be closed - not sure why.

I think I have the code in a separate branch though, so I could open a new pull request if this one has gone completely cold.

**Comment by g-oikonomou** [comment]
I think Pere closed one and opened another at some point. There should a newer one

**Comment by adamdunkels** [comment]
Yeah, that's what I thought too, but there is none in the list: https://github.com/contiki-os/contiki/pulls?utf8=%E2%9C%93&q=is%3Apr+openmote

This pull request is based on the OpenMote:master branch, so it is really easy to simply overwrite the master branch and suddenly the pull request inadvertently goes away.

**Comment by laurentderu** [comment]
Is there someone still actively maintaining this PR and platform ? The refactoring of startup-gcc.c needs to be applied or the OpenMote does not start anymore.

**Comment by AntiCatCH** [comment]
@peretuset I'm still heavily using OpenMotes. Recently I moved to the latest Contiki version. For this reason I cleaned up the platform specific files https://github.com/drandreas/contiki/tree/openmote/platform/openmote. If there is interest I can polish it a little further.

**Comment by drandreas** [comment]
@peretuset I'm still heavily using OpenMotes. Recently I moved to the latest Contiki version. For this reason I cleaned up the platform specific files https://github.com/drandreas/contiki/tree/openmote/platform/openmote. If there is interest I can polish it a little further. (Sorry about the double post, my accounts sometimes get mixed up.)

**Comment by peretuset** [comment]
Dear all,
As said in my previous email, I have been very busy lately and could not
devote much time to fixing the current issues and integrating the code to
the main branch.
However, I expect this situation to change soon and you should expect a
pull request to be integrated in the Contiki main line during this month.
Kind regards,
Pere

2015-12-23 13:01 GMT+01:00 Andreas Dröscher <notifications@github.com>:

**Comment by g-oikonomou** [comment]
#1590

**Pull request closed without merging**
