### PR TITLE
Fixed COOJA to avoid using UI based message list when not using UI.

### PR DESCRIPTION
**Pull request by joakimeriksson**
This hopefully fixes a few of the last parts of the COOJA code that still made use of the MessageList with UI that sometimes cause strange class cast exceptions when running in travis. Fixing the parts of the code that cause the problems that is mentioned in PR #1986.

### CODE REVIEW

**Comment by simonduq** [comment]
Bugfix needed.
@yatch do you have any comment on the content?

**Comment by yatch** [comment]
I believe @joakimeriksson did resolve the issue in a right way ;-)

**Comment by simonduq** [comment]
Now I read the related discussions I also agree. Setting timeout 👍

**Comment by simonduq** [comment]
@nvt could you also take a look at this?

**Comment by nfi** [comment]
I found a few more places where COOJA code still used the UI MessageList and @joakimeriksson has already merged those changes into this PR.

This PR should solve some of the Travis issues and I think it looks good.

**Comment by simonduq** [comment]
OK, enough trusted opinions here, merging now!
Thanks :)

**Comment by yatch** [comment]
This issue, https://github.com/contiki-os/contiki/issues/819 , can be also closed?

**Comment by simonduq** [comment]
I think so!

**Comment by yatch** [comment]
@simonduq Thanks for closing the issue :-)

**Pull request merged**
