### PR TITLE
Harmonize RF_CHANNEL definition

### PR DESCRIPTION
**Pull request by alignan**
This PR brings back the `RF_CHANNEL` configuration parameter to newly platforms missing this, towards having a common channel definition to avoid platform-specific overrides.

@simonduq  `MICROMAC_CONF_CHANNEL` is the jn516x channel definition?

### CODE REVIEW

**Comment by simonduq** [comment]
Yes it is (micromac is the name of the NXP lib that exposes radio capabilities)

**Comment by simonduq** [comment]
do you want to add this to jn516x too then?

**Comment by alignan** [comment]
Yes of course, I will add the `jn516x` as well, I will take another check and try to include more platforms as well

**Comment by alignan** [comment]
Sorry for the delay ( I hate October...), I will update the PR today

**Comment by simonduq** [comment]
ping? ;)

**Comment by alignan** [comment]
Updated, sorry for the very _looong_ reply

**Comment by simonduq** [comment]
:+1: setting timeout for merging

**Comment by alignan** [comment]
No reason to wait longer :+1:

**Pull request merged**
