### PR TITLE
Cleanup some trailing spaces and convert tabs to spaces

### PR DESCRIPTION
**Pull request by tsparber**
This commit removes all trailing spaces and converts
tabs to spaces in files affected by fix-doxygen PR (#1344).

Most indentations are also fixed.

Adding ?w=1 to the url hides all white space only changes.

### CODE REVIEW

**Comment by simonduq** [comment]
would you prefer to have this merged before or after https://github.com/contiki-os/contiki/pull/1344 ? (from a conflict resolution point of view)

**Comment by tsparber** [comment]
It should be merge-able in any order (I just tried both variants on a local branch, merged without conflicts). I'm ok with any order :smiley:

**Comment by simonduq** [comment]
:+1:

**Comment by oliverschmidt** [comment]
:+1:

**Pull request merged**
