### PR TITLE
Avr fixes

### PR DESCRIPTION
**Pull request by drugo72**
The avr-raven platform is in a bad shape. Some projects, e.g. er-rest-example, do not even compile.

Another issue is that when used with the Cetic 6lbr border router, the computation of the RPL DAO lifecycle timer was incorrect due to the limited clock_time_t width of the avr-raven and the default, relatively large values, of the DIO default lifecycle and lifecycle unit used by the Cetic 6lbr (30 and 256 respectively).

Finally, with recent avr-gcc compiles, the avr-ravelcd arrays need to be declared const.

### CODE REVIEW

**Comment by simonduq** [comment]
No interest raised, and this doesn't pass the tests. Will close in one month if there is no more activity.
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by cdealti** [comment]
1. All but the the last four commits are bug fixes. These used to pass the tests. No interest in fixing the raven?

2. The last four commits add support for a temperature and battery sensor on the raven so that interacting with er-rest-example shows something interesting about the raven. These are probably not passing the tests.

Do yuo want me to try to fix #2?

**Comment by simonduq** [comment]
Regarding 1) we are always interested in fixing what is in the code base. The problem is, this particular platform isn't very active, and we didn't get any review on this so far. @malvira, could you please look at this PR?
Regarding 2), this seems pretty unrelated. Also, this seems not raven-specific, so if you are still keen on it, I'll invite you to submit it in a separate pull request. Whether you do the new PR or not, the new CoAP resources should be removed from this PR (to align the focus with the PR title, and to get Travis to pass again)

**Comment by simonduq** [comment]
As this includes bug fixes, I'm adding the bug tag and removing the timeout. No automatic decision in one month. But please take the new CoAP features out of this and make sure Travis gets green. Thanks!

**Comment by cdealti** [comment]
I've reverted the commits described above in 2). Please note that I pushed a final merge commit to sync with the upstream contiki master branch. Is this OK?

I'll create a different PR for 2) only affecting the avr-raven.

Regards

**Comment by cmorty** [comment]
@cdealti Never merge in a pull-request. Always rebase. There documentation on the wiki about that.

**Comment by cdealti** [comment]
@simonduq thanks, removed coap related commits (another PR will follow for these)
@cmorty thanks, rebased.

**Comment by simonduq** [comment]
@malvira can you please take a look?

**Comment by malvira** [comment]
Can you factor c14caf4699b77392525afdf304d260fe431b6db9 and 69da9e25f956d630f398ac8b75e216063ad5e669 in to a separate PR as they are changes to RPL and not AVR specific? Assuming the core mergers pull in those changes then we can do the rest of the AVR changes.

**Comment by drugo72** [comment]
@malvira thanks, rebased.
RPL specific commits moved to https://github.com/contiki-os/contiki/pull/1271

**Comment by simonduq** [comment]
@malvira, shall we merge?

**Pull request merged**
