### PR TITLE
Coaprelay

### PR DESCRIPTION
**Pull request by DeshpandeChandana**
added coap-LED-GET-PUT folder

### CODE REVIEW

**Comment by vsaw** [comment]
Something seems to have gotten out of hand, unless of course you really want 10k lines of code to be committed?

**Comment by DeshpandeChandana** [comment]
Hi, What do u think is out of hand??

**Comment by vsaw** [comment]
I think the pull request is based on a outdated branch since you seem to revert all the contiki version string changes that came with the 3.0 release. Just [check the diff](https://github.com/contiki-os/contiki/pull/1270/files) and you will see.

**Comment by laurentderu** [comment]
Looks like an internal PR pushed towards Contiki by mistake. If not, could you please rebase on latest Contiki, clean up your commits and provides a good documentation about this PR ?

**Pull request closed without merging**
