### PR TITLE
Rime Chameleon fix for 32-bit platforms

### PR DESCRIPTION
**Pull request by simonduq**
use BITOPT_HDR_SIZE rather than sizeof(struct bitopt_hdr)

### CODE REVIEW

**Comment by tonnenpinguin** [comment]
Out of curiosity: Why is using the preprocessor define in this case better than using sizeof?

**Comment by simonduq** [comment]
Because ` sizeof(struct bitopt_hdr))` is 4 on 32-bit platforms (rounds up to word size), while the real, intended bitopt header size is 2.

**Comment by simonduq** [comment]
A consequence is that a 32-bit node and a 16-bit node won't be able to communicate as they will work on different header sizes.

**Comment by tonnenpinguin** [comment]
I see, I see..
Thanks for the explanation!

**Comment by tonnenpinguin** [comment]
One more question though: Is this sizeof behaviour compiler specific?
I just tried it on my CC2650 (which is 32 Bit AFAIK) and sizeof returns 2..

**Comment by simonduq** [comment]
I think it is compiler-specific yes, what it returns is the size the struct will actually take in memory.
Interesting that you get 2 on Cortex M3, I would have guessed 4.
In our case the problem arose on JN516x, where it was 4.

**Comment by tonnenpinguin** [comment]
I've only seen this varying code size when the compiler needs to do some padding...really interesting indeed! Learn something new every day I guess!

**Pull request merged**
