### PR TITLE
oma-lwm2m: Use sv for string value, bv for boolean

### PR DESCRIPTION
**Pull request by gebart**
This fixes JSON parsing errors when reading entire instances from the Leshan example server web GUI.

http://dev_devtoolkit.openmobilealliance.org/IoT/LWM2M10/doc/TS/index.html#!Documents/json.htm

### CODE REVIEW

**Comment by joakimeriksson** [comment]
Looks like good improvements! 👍

**Comment by alignan** [comment]
:+1:

Travis failure is unrelated, restarting anyway

**Comment by joakimeriksson** [comment]
Yes this failure seems totally unrelated.

**Comment by nvt** [comment]
:+1:

**Pull request merged**
