### PR TITLE
CC2538: Allow for configuration of processor clocks

### PR DESCRIPTION
**Pull request by uknoblic**
Allow for configuration of processor speed using configuration parameters for system and I/O clock. (Re-pull request for https://github.com/contiki-os/contiki/pull/1044). Added two new macros in sys-ctrl.h (SYS_CTRL_CONF_SYS_DIV and SYS_CTRL_CONF_IO_DIV) and modified clock dependent modules accordingly.

### CODE REVIEW

**Comment by bthebaudeau** [comment]
Good. The  change for the UART is now done too.

There is still one tab to be changed into spaces after `RTIMER_CLOCK_TICK_RATIO`. Make sure there aren't others.

There is still SPI_CC to be set to 0 to use the system clock, and the SPI clock should be configured in order not to change if the system clock is changed. But maybe this can go to another PR. @g-oikonomou What do you think? I think that at least SPI_CC should be set to 0 here in order not to have missing `#error` rules on the clock restrictions, which means that this PR or #1042 has to wait for the other one and be rebased.

**Comment by bthebaudeau** [comment]
Good. Now waiting for #1042 merger to rebase this one and set SPI_CC to 0.

**Comment by bthebaudeau** [comment]
Now that #1042 has been merged, you can set SPI_CC to 0 in the commit here.

**Comment by bthebaudeau** [comment]
:+1:

Thanks for your efforts!

**Comment by uknoblic** [comment]
And your patience ;-)

**Pull request merged**
