### PR TITLE
Basic NETSTACK_CONF_RADIO based on kernel 802.15.4

### PR DESCRIPTION
**Pull request by farcaller**
This CL adds a basic NETSTACK_CONF_RADIO implementation based on linux kernel 802.15.4 radio stack, allowing to offload 802.15.4 to kernelspace, e.g. use native contiki in router mode with mrf24j40 sitting in SPI and being handled by kernel.

The patch is WIP, so your advice on how to clean it up for submission would be much appreciated.

### CODE REVIEW

**Comment by simonduq** [comment]
@nvt do you still think this is relevant and ready to be merged?
If so, @farcaller, you'll need to rebase and we'll merge.
If not, will have close in one month.
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by farcaller** [comment]
whow, it was a while. I guess I need to make sure it even works.

**Comment by simonduq** [comment]
Sounds like a good idea :) (probably worth it given the time you invested back then)
Thanks

**Comment by simonduq** [comment]
not rebased, closing

**Comment by farcaller** [comment]
Sorry, this slipped off my radar. Rebased now.

**Comment by simonduq** [comment]
ok, I cannot seem to re-open, please re-open yourself and let's see what Travis has to say!

**Comment by farcaller** [comment]
Can't re-open either, forked to #1282.

**Pull request closed without merging**
