### PR TITLE
Make Random simulation thread safe

### PR DESCRIPTION
**Pull request by cmorty**
This ensures that simulations are reproducable.
This is the aftermath of https://github.com/contiki-os/contiki/pull/810 and https://github.com/contiki-os/contiki/pull/821

Will rebase this, once #810 is merged.

### CODE REVIEW

**Comment by simonduq** [comment]
@cmorty, is this ready for @fros4943 to check and merge?
No activity during a month will result in closing
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by cmorty** [comment]
@simonduq , @fros4943: Yes. I'm happy with it. Didn't help me find the cause of different simulation results on different systems, but will rule out the PRNG in future.

**Comment by simonduq** [comment]
OK then given @fros4943's earlier comment, I guess this is good for merging, but let him confirm and merge.

**Comment by fros4943** [comment]
Yep, good for merging! :+1:

**Pull request merged**
