### PR TITLE
Add DODAG lifetime, update of parent rank when switching dag and multi dodag non-regression test

### PR DESCRIPTION
**Pull request by laurentderu**
Currently there is no automated way to remove obsolete DODAG in a node, if a node has seen MAX_DODAG_PER_INSTANCE DODAGS all new DODAG are ignored, the only way to remove the old DODAG is to reset the node.

This PR add a lifetime for each DODAG, the lifetime is reset each time a DIO advertising that DODAG is heard. When a DODAG is not updated since RPL_CONF_DAG_LIFETIME the DODAG is removed from the list. Note that the currently joined DODAG is immunized from this.

### CODE REVIEW

**Comment by nvt** [comment]
I think that it is good to have a GC on unused DODAGs, but the comment describing this option should say why it exists, and in what unit the life time is. Is a uint32_t necessary to store a life time of this sort?

**Comment by laurentderu** [comment]
Comments updated accordingly. The lifetime should be a uint32_t, uint16_t would give us only 65535 seconds (2/3rd of a day), which could be too short for DODAG with long DIO interval.

**Comment by laurentderu** [comment]
Sky rom overflow is solved after rebase, travis is now happy.

**Comment by simonduq** [comment]
Looks good but isn't the default lifetime a bit short? 20 min is close to the default longest DIO period, meaning a node with very few neighbors could easily end up freeing a DODAG that is still active, right?

**Comment by laurentderu** [comment]
Indeed, a node could free a usable dodag because it has missed a few DIO. I could update the timeout to a larger value, let say one hour, or derive the timeout from the default max interval times a constant (maybe 3). What do you think ?

**Comment by simonduq** [comment]
I'm equally fine with a longer time such as 1h or some multiplicator of the max interval of the instance (learnt from DIO rather than the compile-time default default)

**Comment by simonduq** [comment]
@laurentderu, if you find the time to fix this (just set a longer lifetime) and rebase, I'll merge happily after a month!
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by laurentderu** [comment]
The longer time will not work if the DIO interval of the second DODAG is longer than it, so the only safe solution is to have a multiplicator of the max interval of the DODAG. I'm validating the modification and will update the PR.

**Comment by simonduq** [comment]
sounds great!

**Comment by simonduq** [comment]
any update @laurentderu?

**Comment by laurentderu** [comment]
I updated the code, now the DAG lifetime is linked to the maximum DIO interval.

I added a non-regression test to validate multi-dodag support and dodag lifetime, it successively creates and removes 3 RPL Root and check that there is still connectivity afterwards.

However this non-regression test let me discover another issue related to multi-dodag : If a known parent switch from one dodag to another (new or existing), the rank of that parent is not updated and still the rank in its former dodag. This can lead to dead-lock in part of the tree as a parent with infinite rank in a previous dag can not become a parent in the new dag as the old rank is unacceptable.

**Comment by simonduq** [comment]
OK, do you agree this is still good to merge anyway?
Maybe you should open an issue with the problem described here?

**Comment by laurentderu** [comment]
I forgot that a change in the list of commits is not visible. I already added the fix and the non-regression test in this PR.

**Comment by simonduq** [comment]
Looks good, waiting a little more before merging so people have time to comment on the additional fix

**Comment by simonduq** [comment]
merging now

**Pull request merged**
