### PR TITLE
Support more than one pending slip message

### PR DESCRIPTION
**Pull request by laurentderu**
Currently, the slip buffer can contain only one pending packet, which means that if there is a burst of packets coming from the BR all but the first are discarded. This PR transforms the slip buffer into a circular buffer able to store an unlimited number of packets (as long as they fit into the buffer)

### CODE REVIEW

**Comment by simonduq** [comment]
Excellent feature! How thoroughly has this been tested?

**Comment by laurentderu** [comment]
It has been used in 6LBR since quite a long time, so I think it's quite stable and it increase the packet reception rate quite significantly.
However, looking again at the diff more than a year later make me think that some refactoring could make the code more readable.

**Comment by simonduq** [comment]
OK in that case I think you should just go ahead and merge that one when you're done reworking it

**Comment by simonduq** [comment]
@laurentderu shall we merge this one?

**Comment by neophob** [comment]
:+1:

**Comment by laurentderu** [comment]
The code is not really optimized but I guess it's better in than lingering out...

**Comment by alignan** [comment]
:+1:

**Comment by simonduq** [comment]
The only thing that stops me from adding :+1: now is that SLIP is not covered by regression tests, so I'd like @laurentderu to confirm the version in this PR is a well-tested one.

**Comment by alignan** [comment]
I think he already confirmed that, as it has been used in 6lbr

**Comment by simonduq** [comment]
Right, sorry for some reason I assumed this had been rebased in between but this is not the case indeed

**Comment by simonduq** [comment]
:+1:

**Comment by laurentderu** [comment]
I will try to improve the slip-radio non-regression tests and submit a new PR for them soon

**Comment by simonduq** [comment]
sounds great!

**Pull request merged**
