### PR TITLE
Adjust CC26xx/CC13xx ADC reading for gain and offset

### PR DESCRIPTION
**Pull request by t-than**

### CODE REVIEW

**Comment by g-oikonomou** [comment]
This looks reasonable, thanks.

**Comment by g-oikonomou** [comment]
Do you think you could put the code through uncrustify?

**Comment by t-than** [comment]
I haven't done it before, but I am more than willing to try.

**Comment by g-oikonomou** [comment]
https://github.com/contiki-os/contiki/wiki/Code-Contributions#code-formatting

Just push -f using the same branch when you are ready.

**Comment by g-oikonomou** [comment]
👍

**Pull request merged**
