### PR TITLE
packetbuf cleanup

### PR DESCRIPTION
**Pull request by kkrentz**
This pull request removes unnecessary `packetbuf` functions.

### CODE REVIEW

**Comment by simonduq** [comment]
Removing `packetbuf_compact`while `packetbuf_hdrreduce` is still in use seems wrong to me. Am I missing something?

**Comment by kkrentz** [comment]
Maybe it is wrong. Anyway, what is strange is that `packetbuf_compact` is called very inconsistently. For example, `packetbuf_compact` is called by `cxmac`, but not by `nullrdc`. Apparently, the most appropriate place to call `packetbuf_compact` is then a packet changes its direction because, at this point, the hdrreduce calls should be done and hdralloc calls should begin. The reason why everything works even without `packetbuf_compact` seems to be that `packetbuf_copyto` does the job of `packetbuf_compact` as a side effect, which is also strange. Perhaps you have a better idea to clean up these things.

**Comment by simonduq** [comment]
I would also like a cleanup but am equally confused with this feature of packetbuf...

**Comment by kkrentz** [comment]
I restored `packetbuf_compact` - now these changes should do no harm

**Comment by simonduq** [comment]
:+1:

**Comment by simonduq** [comment]
merging after timeout

**Pull request merged**
