### PR TITLE
DAD: Remove useless "if" that tests if the source address is unspecified

### PR DESCRIPTION
**Pull request by MohamedSeliem**
No need to do the unspecified address twice.
# if UIP_ND6_DEF_MAXDADNS > 0

```
if(uip_is_addr_unspecified(&UIP_IP_BUF->srcipaddr)) {
  /* DAD CASE */
   ..........
```
# else /\* UIP_ND6_DEF_MAXDADNS > 0 */

```
if(uip_is_addr_unspecified(&UIP_IP_BUF->srcipaddr)) {
  /* DAD CASE */
  goto discard; 
```
# endif /\* UIP_ND6_DEF_MAXDADNS > 0 */

this logic will bring confusion, especially when someone try to understand the implementation of other ND functions (NUD, address resolution)  .

### CODE REVIEW

**Comment by MohamedSeliem** [comment]
@simonduq any feedback on this
Thanks

**Comment by simonduq** [comment]
looks good to me :+1:

**Comment by MohamedSeliem** [comment]
@nvt @simonduq any plans to merge this soon.

**Comment by simonduq** [comment]
see https://github.com/contiki-os/contiki/blob/master/CONTRIBUTING.md#pull-request-merging-policy

**Comment by nvt** [comment]
Looks reasonable. :+1:

**Pull request merged**
