### PR TITLE
cc2538: Add support for Coffee

### PR DESCRIPTION
**Pull request by bthebaudeau**
This pull request adds support for Coffee. The first commits improve the CC2538 infrastructure in order to make it easier to support Coffee in the last commit, but the CC2538 support also generally benefits from these improvements.

This PR has been build-tested. The Coffee port has also been runtime-tested in another context, but not with this PR. This PR can be runtime-tested using https://github.com/contiki-os/contiki/wiki/Coffee-filesystem-example#coffeeexamplec, after having defined `COFFEE_CONF_SIZE` (e.g. `(4 * COFFEE_SECTOR_SIZE)`) and maybe (but this does not seem to be necessary for this example) some other `COFFEE_CONF_*` to something useful in `project-conf.h`.

### CODE REVIEW

**Comment by alignan** [comment]
Great! I will test it as soon as I can.

**Comment by bthebaudeau** [comment]
Note that this example does not format Coffee, so you may have to add a call to `cfs_coffee_format();` at the beginning of this example depending on how you program this example on the device (i.e. chip erase vs. N x page erase).

Note that I will add two minor things in an update.

**Comment by bthebaudeau** [comment]
I've just pushed an update adding:
 - Coffee as a feature in the CC2538 platforms `README.md`,
 - `COFFEE_CONF_CUSTOM_PORT` (see the last commit message),
 - comments to the last commit message.

**Comment by bthebaudeau** [comment]
I approve this PR. If nobody disapproves within one month, I will merge it. I'm just not certain whether this rule also applies if the PR author is the merging maintainer.

**Comment by simonduq** [comment]
That's ok IMO, as long as you're confident enough. There is month for all others to react.

**Comment by bthebaudeau** [comment]
@simonduq Yes, I'm pretty confident, but some testing wouldn't hurt, though. We'll see in one month.

**Comment by alignan** [comment]
I have been testing this PR, I still need to tweak the configuration, but overall the PR is very complete and I will be happy to merge it myself, unfortunately we have a very high work load right now.  @bthebaudeau do you mind if I contact you offline and see how we can speed up this?

**Comment by bthebaudeau** [comment]
@alignan

> I have been testing this PR, I still need to tweak the configuration, but overall the PR is very complete and I will be happy to merge it myself, unfortunately we have a very high work load right now.

There's still one month to go, so no extreme hurry.

> @bthebaudeau do you mind if I contact you offline and see how we can speed up this?

That's fine by me.

**Comment by alignan** [comment]
Needs rebasing

**Comment by bthebaudeau** [comment]
Rebased.

I had a lot of issues with the recent line ending changes, especially with `tools/cooja/java/org/contikios/cooja/util/CCITT_CRC.java`.

**Comment by sieben** [comment]
@bthebaudeau I had the same problem as well...

**Comment by bthebaudeau** [comment]
I've just pushed a rebased update. It adds a new commit (the last but one) to support flashing any .bin files, especially the ones generated using Coffee with the last commit.

@alignan Can you test this new version please? Rúnar successfully tested the previous version, and the only difference is this new commit.

**Comment by alignan** [comment]
````
step 1: #1.hello world.
step 2: successfully written to cfs. wrote 32 bytes
step 3: #1.hello world.
step 4: successfully appended data to cfs. wrote 32 bytes  
step 5: #1 - #1.hello world.
step 5: #2 - #2.contiki is amazing!
Successfully removed file
````
We should add the coffee example anyway as it is already in the wiki.
:+1:

**Comment by g-oikonomou** [comment]
What version of the cc2538-bsl script was used to test this before merging?

**Comment by g-oikonomou** [comment]
```
$ make cc2538-demo.upload
using saved target 'cc2538dk'
  CC        ../../cpu/cc2538/./ieee-addr.c
  AR        contiki-cc2538dk.a
  CC        ../../cpu/cc2538/cc2538.lds
  CC        ../../cpu/cc2538/./startup-gcc.c
  CC        cc2538-demo.c
  LD        cc2538-demo.elf
arm-none-eabi-objcopy -O binary --gap-fill 0xff cc2538-demo.elf cc2538-demo.bin
python ../../tools/cc2538-bsl/cc2538-bsl.py -e -w -v -a $(arm-none-eabi-objdump -h cc2538-demo.elf | sed -n '/\<LOAD\>/{g;1!p;};h' | awk '{print "0x" $5}' | sort -g | head -1) cc2538-demo.bin
Traceback (most recent call last):
  File "../../tools/cc2538-bsl/cc2538-bsl.py", line 526, in <module>
    conf['address'] = eval(a)
  File "<string>", line 1, in <module>
NameError: name 'cc2538' is not defined
make: *** [cc2538-demo.upload] Error 1
rm cc2538-demo.co obj_cc2538dk/startup-gcc.o
```

**Comment by bthebaudeau** [comment]
1223bfe, like in the current Contiki master. I see two possible causes for this error:
- your OS does not support some part of the command (run it manually step by step to see what it gives on your machine),
- you're working on #1361, your submodule is not synced with master, and there is something new in the script breaking things.

**Comment by g-oikonomou** [comment]
```
$ arm-none-eabi-objdump -h cc2538-demo.elf

cc2538-demo.elf:     file format elf32-littlearm

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         00004b19  00200000  00200000  00008000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .socdata      00000040  20000000  20000000  00018000  2**2
                  ALLOC
  2 .data         000000c9  20000040  00204b1c  00010040  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  3 .ARM.exidx    00000008  00204be8  00204be8  00014be8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .bss          00000cef  20000110  20000110  00018000  2**3
                  ALLOC
  5 .stack        00000800  20000e00  20000e00  00018000  2**2
                  ALLOC
  6 .flashcca     0000002c  0027ffd4  0027ffd4  00017fd4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 .comment      00000070  00000000  00000000  00018000  2**0
                  CONTENTS, READONLY
  8 .ARM.attributes 00000031  00000000  00000000  00018070  2**0
                  CONTENTS, READONLY
  9 .debug_frame  00000150  00000000  00000000  000180a4  2**2
                  CONTENTS, READONLY, DEBUGGING
$ arm-none-eabi-objdump -h cc2538-demo.elf | sed -n '/\<LOAD\>/{g;1!p;};h'
$ 
```

**Comment by JelmerT** [comment]
Same problem here

```
$ arm-none-eabi-objdump -h cc2538-demo.elf

cc2538-demo.elf:     file format elf32-littlearm

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .text         00004b05  00200000  00200000  00008000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .socdata      00000040  20000000  20000000  00018000  2**2
                  ALLOC
  2 .data         000000c9  20000040  00204b08  00010040  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  3 .ARM.exidx    00000008  00204bd4  00204bd4  00014bd4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .bss          00000cef  20000110  20000110  00018000  2**3
                  ALLOC
  5 .stack        00000800  20000e00  20000e00  00018000  2**2
                  ALLOC
  6 .flashcca     0000002c  0027ffd4  0027ffd4  00017fd4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 .comment      00000070  00000000  00000000  00018000  2**0
                  CONTENTS, READONLY
  8 .ARM.attributes 00000031  00000000  00000000  00018070  2**0
                  CONTENTS, READONLY
  9 .debug_frame  00000118  00000000  00000000  000180a4  2**2
                  CONTENTS, READONLY, DEBUGGING
```
and 
```
$ arm-none-eabi-objdump -h cc2538-demo.elf | sed -n '/\<LOAD\>/{g;1!p;};h'
```
has no output.
```
$ arm-none-eabi-objdump -v
GNU objdump (GNU Tools for ARM Embedded Processors) 2.23.2.20131129
```

**Comment by alignan** [comment]
What OS are you using?

**Comment by alignan** [comment]
Mmm in my VM box I get:

````
$ arm-none-eabi-objdump -h zoul-demo.elf  | sed -n '/\<LOAD\>/{g;1!p;};h'  0 .text         00004b92  00278000  00278000  00008000  2**2
  2 .data         000000b9  20004040  0027cb94  00014040  2**2
  3 .ARM.exidx    00000008  0027cc50  0027cc50  00014c50  2**2
  6 .flashcca     0000002c  0027ffd4  0027ffd4  00017fd4  2**2

$ python ../../../tools/cc2538-bsl/cc2538-bsl.py -e -w -v -a $(arm-none-eabi-objdump -h zoul-demo.elf | sed -n '/\<LOAD\>/{g;1!p;};h' | awk '{print "0x" $5}' | sort -g | head -1) 
ERROR: No file path given.
````
But when I tested on my Ubuntu native upon merging it worked OK.

**Comment by alignan** [comment]
I just edited my previous comment as I had a typo in the upload command, it works for me in Ubuntu:

````
$ arm-none-eabi-objdump -h zoul-demo.elf | sed -n '/\<LOAD\>/{g;1!p;};h'
  0 .text         00004b92  00278000  00278000  00008000  2**2
  2 .data         000000b9  20004040  0027cb94  00014040  2**2
  3 .ARM.exidx    00000008  0027cc50  0027cc50  00014c50  2**2
  6 .flashcca     0000002c  0027ffd4  0027ffd4  00017fd4  2**2
````
````
$ arm-none-eabi-objdump -v
GNU objdump (GNU Tools for ARM Embedded Processors) 2.24.0.20150304
````

**Comment by g-oikonomou** [comment]
So this has to do with sed on OS X, which is BSD sed.

I can make this thing work by replacing sed with gsed or by `grep -B1 LOAD | grep -Ev 'LOAD|\-\-'`, like so:

```
$ arm-none-eabi-objdump -h cc2538-demo.elf | grep -B1 LOAD | grep -Ev 'LOAD|\-\-' | awk '{print "0x" $5}' | sort -g | head -1
0x00200000
$ arm-none-eabi-objdump -h cc2538-demo.elf | gsed -n '/\<LOAD\>/{g;1!p;};h' | awk '{print "0x" $5}' | sort -g | head -1
0x00200000
```

**Comment by alignan** [comment]
Tested on Ubuntu and works just as fine as `sed`

**Pull request merged**
