### PR TITLE
Use TI-Provided CC13xx/CC26xx RF API

### PR DESCRIPTION
**Pull request by g-oikonomou**
Originally, TI were not shipping RF API headers with CCxxwares, so we had to distribute those through Contiki (files under `cpu/cc26xx-cc13xx/rf-core/api/`).

This changed a while ago. CCxxwares now include API headers for common commands, BLE mode and PROP mode (CC13xxware only). Headers for IEEE mode are not included in CCxxwares yet.

This pull changes our CC13xx/CC26xx ports to use CCxxware-provided headers where possible.

Tested with:
* CC2650 STK
* SmarfRF + CC2650EM
* CC1310LP

Sits on top of #1924

### CODE REVIEW

**Comment by aparvizi** [comment]
HI,
I Test CC1350LP_US, cc26XX webdemo with 6lbr :

(on BBB & raspberry pi)

in IEEE mode :

1) 6lbr up , no problem.
2) web_demo cc1350LP_US connected to 6lbr and get IP's , but no PING .

(6lbr router on BBB & RPI with same config work FINE with CC2650 & ST & CC2358+PA)

on prob mode:
1) 6lbr up , no problem.
2) web_demo cc1350LP_US not connected & stay in blink, not works;

regards,
a.Parvizi

**Comment by alignan** [comment]
Looks good, but I haven't tested myself, waiting for someone else to confirm it is working, @jonnteolsson?

**Comment by g-oikonomou** [comment]
Thanks Antonio, this one works on all my kit and also @arurke reports positive results in #1659, but we are doing some more testing internally over the next couple of days!

**Comment by jonnteolsson** [comment]
I will test this in the coming days and get back to you.

-Jonas

**Comment by jonnteolsson** [comment]
Looks good, tested with CC1350LaunchPad (EU), CC1310LaunchPad (EU) and CC1350SensorTag (US) defualt RF configuration. All looks good, RSSI as expected and stable.

**Comment by g-oikonomou** [comment]
All discussions here as well as under #1932 indicate this is ready to merge.

In addition to the boards listed in the OP, this has also been tested with CC1350LP and CC1350STK

**Comment by EduardoMolinaTomas** [comment]
Maybe is a dumb question but, what board definition have I to use to compile codes for CC1350 devices (sensor tag and launch pad)?

For instance for CC2650 Launchpad I use BOARD=launchpad/cc2650, but as far as I know I can't use BOARD=launchpad/cc1350.

**Comment by g-oikonomou** [comment]
@EduardoMolinaTomas to get support for the CC1350LP, you need #1932 (which sits on top of this PR here)

**Comment by arurke** [comment]
Tested this a bit separately (with one custom cc1310 board + cc1310em as SLIP). No adverse effects seen, and RSSI improved > 10 db. Regarding adverse effect, judging from the updated timings I reckon one should expect ~10 % reduced max. throughput?

**Comment by g-oikonomou** [comment]
@arurke Andreas these updated timings are required because with all the new patching of the RF core the startup time increases a little bit. So perhaps somewhat lower throughput compared to what we have now, but remove the timing chances and performance will go very south.

**Comment by g-oikonomou** [comment]
I'll merge this in a month unless I receive an objection.

**Pull request merged**
