### PR TITLE
Contact

### PR DESCRIPTION
**Pull request by TeVeDe**

### CODE REVIEW

**Comment by cmorty** [comment]
This should probably go into two PRs. The contacts-thing is a no-brainer, while the examples might need a review. Having a very quick glance, it seems like there might be some redundancy that can be removed from the examples. But I might well be wrong.

**Comment by simonduq** [comment]
Yes, the first commit is from https://github.com/contiki-os/contiki/pull/1423, only the second one should be in this PR.

**Comment by TeVeDe** [comment]
I will close this PR and make a separate one with the NXP contacts as suggested

**Comment by cmorty** [comment]
There's documentation on the wiki on how to update an PR.

**Pull request closed without merging**
