### PR TITLE
Fix the leftover mentions of aaaa as a prefix to be UIP_DS6_DEFAULT_PREFIX (now fd00)

### PR DESCRIPTION
**Pull request by MohamedSeliem**

### CODE REVIEW

**Comment by alignan** [comment]
:+1:  as soon as Travis is green

**Comment by MohamedSeliem** [comment]
@alignan 
in cpu/native/net/tapdev6.c
 addreq6.ifra_addr.sin6_addr.__u6_addr.__u6_addr16[0] = UIP_HTONS(0xAAAA);
msg.dst.sin6_addr.__u6_addr.__u6_addr16[0] = UIP_HTONS(0xAAAA);

in cpu/mc1322x/tests/autoack-rx.c
*MACA_MACPANID = 0xaaaa;

i think i should fix these too, what do u think??

**Comment by simonduq** [comment]
please rebase now that https://github.com/contiki-os/contiki/issues/1965 is resolved

**Comment by alignan** [comment]
And also squash the two commits with the same commit message

**Comment by MohamedSeliem** [comment]
👍 done.

**Pull request merged**
