### PR TITLE
feat(ctimer): API extension to explictly state the process a ctimer belongs to

### PR DESCRIPTION
**Pull request by vsaw**

### CODE REVIEW

**Comment by simonduq** [comment]
Looks good to me. I don't understand what the commit message `feat(ctimer)` means though. Can you rebase on the current master and clarify the log?

**Comment by vsaw** [comment]
The commit messages follow the [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.uyo6cb12dt6w). It's my personal preference but I think it's useful :)

**Comment by simonduq** [comment]
Ok you've addressed both Adam's and my concerns, and the code doesn't affect anything else, so :+1: 
Will merge in a month if nobody argues. Rebase probably not strictly needed here but appreciated if you do.
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by vsaw** [comment]
@simonduq It has been rebased.

**Comment by simonduq** [comment]
Thanks!

**Comment by adamdunkels** [comment]
:+1:

**Pull request merged**
