### PR TITLE
fix ipv6 http socket host handling as in RFC2732

### PR DESCRIPTION
**Pull request by casaroli**
sorry I had to create a new PR.

### CODE REVIEW

**Comment by vsaw** [comment]
This is actually not related to your code but I was wondering if you might fix this as well to make your pull-request more robust:

The problem is that the [`parse_url`](https://github.com/momote-io/contiki/blob/03ca795bd6c163eaed116a129ec4d1a53833700c/core/net/http-socket/http-socket.c#L292) might not `\0` terminate the `host` string. The way I see it: If it is passed an URL, where the host is longer than `MAX_HOSTLEN`, then the host string will not be terminated.

Two things should be done to fix this.

1. [`parse_url`](https://github.com/momote-io/contiki/blob/03ca795bd6c163eaed116a129ec4d1a53833700c/core/net/http-socket/http-socket.c#L292)  should check if the host fits into the destination buffer and return the error value `0` if it did not.
2. Your code should consider using [`memchr`](http://www.cplusplus.com/reference/cstring/memchr/) and first check for the `\0` termination before looking for IPv6 addresses.

Ideally [`parse_url`](https://github.com/momote-io/contiki/blob/03ca795bd6c163eaed116a129ec4d1a53833700c/core/net/http-socket/http-socket.c#L292)   should also get the size of the host buffer to remove the assumption that the host and path buffers have a certain size.

**Comment by casaroli** [comment]
@vsaw thanks for the comments.

I now included a check for the \0 char but I think it was simpler to add _just after_ the parsing.

I also changed the my functions to use memchr instead of srdchr.

What do you think?

BR

**Comment by vsaw** [comment]
I'd still prefer having `parse_url` fixed as this is an IMHO unsafe function if used wrong.
But at least your code is now fixed 👍

**Comment by simonduq** [comment]
Looks good to me except for code style: please remove spaces between `if` and `(`

**Comment by casaroli** [comment]
Fixed code style.

@vsaw The first check fixes exactly the parse_url function. I don't see a problem anymore. Is there anything I could do better for that fix?

BR

**Comment by vsaw** [comment]
The danger I see with `parse_url` is that your code invokes it correctly. However it is invoked in two more place which might not take all the precaution you did.

Therefore I would have loved seeing a more "defensive" behaviour of `parse_url`, so that it becomes easier to use the function correctly.

**Comment by simonduq** [comment]
I feel this is a fair concern @vsaw but could go in a different PR, what do you think?

**Comment by vsaw** [comment]
@simonduq Sure.

**Comment by alignan** [comment]
Could you please create an issue about `parse_url` being unsage? just to keep this up.

**Comment by vsaw** [comment]
@alignan Done. See https://github.com/contiki-os/contiki/issues/1707

**Comment by alignan** [comment]
@vsaw Thanks!

:+1:

**Comment by simonduq** [comment]
Thanks! :+1:

**Pull request merged**
