### PR TITLE
TSCH Miscelleneous updates

### PR DESCRIPTION
**Pull request by yatch**
- Put `tsch_` prefix to some global names
- Add the const modifier to dest addr in tsch_packet_create_eack()
- Add missing error checks / fix a wrong return value
- Add regression tests for APIs in implemented `tsch-packet.c`
- Indentation fixes

### CODE REVIEW

**Comment by simonduq** [comment]
👍

**Comment by nvt** [comment]
:+1:

**Comment by yatch** [comment]
@nvt Indeed. I'll resolve the conflicts soon.

**Comment by yatch** [comment]
The conflicts have been resolved. And, Travis got green. 😄

**Comment by alignan** [comment]
:+1:

**Pull request merged**
