### PR TITLE
some additions to tunslip6 to make it a bit easier to diagnose problems with it

### PR DESCRIPTION
**Pull request by mcr**
An additional important thing is to be able to reliably see console messages from contiki which may be interspersed into the code IP packets.

### CODE REVIEW

**Comment by laurentderu** [comment]
I see nothing wrong at first sight. @mcr are you still interested about this PR, if so could you rebase it ?

**Comment by mcr** [comment]
I can rebase by Monday.

**Comment by simonduq** [comment]
Nice, I'll merge in a month if nobody speaks against this PR
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by fvdnabee** [comment]
Just a quick question, why is the default behaviour to enable IPA? It seems to me that a more sensible default behaviour would be to disable IPA (and enabling it via a flag), as in the default rpl-border-router example the IPA message is not processed. With the default rpl-border-router, enabling IPA leads to "Got request message of type I" being echoed over and over again (see slip-bridge.c https://github.com/contiki-os/contiki/blob/master/examples/ipv6/rpl-border-router/slip-bridge.c#L74 ).

Unless I'm missing something, I would suggest changing the behaviour of the I flag to enable IPA rather than disabling it.

**Comment by simonduq** [comment]
Yes, that's included in https://github.com/contiki-os/contiki/pull/1304

**Pull request merged**
