### PR TITLE
RPL large-scale test & bugfix

### PR DESCRIPTION
**Pull request by adamdunkels**
This patch contains a test with a too-large RPL network and one RPL  bugfix.

# Too large RPL test
The RPL mesh should be able to support more nodes than the number of neighbor table entries and routing table entries.

This patch adds a test where 50 nodes attempt to do an HTTP socket connection to download the Contiki web page. The network is configured to have 3 neighbor table entries and routing table entries, except for the gateway node which has 8 entries.

Once the HTTP socket has downloaded its data, it sets the node into RPL feather mode, in which the network drops all direct routes to the node.

To make this work, this patch also adds a NOPATH DAO transmission when a node transitions into feather mode.

# RPL bugfix
The RPL ICMPv6 input handling code should drop incoming packets that it cannot handle, such as DIOs and DAOs, but the code currently does not actually drop them. Instead, the packets are forwarded unchanged, which will cause problems for nodes that receive them. This is particularly bad for DAOs, as the receiving node will get a bad route (because the receiving node believes that the erroneously forwarding node is a valid route). The fix is to ensure that `uip_len` is set to `0` every time a packet should be dropped. This patch fixes that.

### CODE REVIEW

**Comment by joakimeriksson** [comment]
Good - I have also seen that bug! It was introduced when we moved from the switch that switched on the different RPL messages over to the ICMP handlers.

**Comment by laurentderu** [comment]
see https://github.com/contiki-os/contiki/issues/1106 ;) I was waiting for https://github.com/contiki-os/contiki/pull/1116 to fix it

**Comment by adamdunkels** [comment]
@laurentderu nice! This should definitely fix #1106! And should be possible to simply this one after #1116.

**Comment by adamdunkels** [comment]
Rebased on top of #1116

**Comment by simonduq** [comment]
:+1: (if Travis is green)

**Comment by adamdunkels** [comment]
Travis was green before rebasing - let's hope it still is :)

**Comment by adamdunkels** [comment]
Travis is green!

**Comment by fros4943** [comment]
:+1:

**Comment by joakimeriksson** [comment]
Is it fairly easy to run this test in Instant Contiki? - I did a quick try but there are things failing (wpcap-slip location, etc)? I would prefer to debug locally rather than sending up to github for complete travis runs to speed up the development and to avoid spending travis CPU cycles when not needed.

**Comment by adamdunkels** [comment]
Yes it runs nicely in Instant Contiki. One thing may need to be altered though is the `CMD_PATH` on line 12 in `testscript.js`. It should be either `"../../wpcapslip"` or `"../../../wpcapslip"` depending on whether the test is run from within Cooja or by running `make` in the test directory.

**Comment by joakimeriksson** [comment]
Yes, I think I am getting it to run now (it gets further at least)! Thanks.

**Comment by joakimeriksson** [comment]
Now I can run the simulation in COOJA and see that it is close but a bit slower than the test requires (I have made some minor modifications to the neighbor policy). It ends like this:
---
Data compelete 24, heard 28 in total
Data compelete 16, heard 29 in total
Data compelete 19, heard 30 in total
TEST TIMEOUT
TEST FAILED
---

**Pull request merged**
