### PR TITLE
TSCH port for Zolertia ReMote/Zoul.

### PR DESCRIPTION
**Pull request by sumanpanchal**

### CODE REVIEW

**Comment by simonduq** [comment]
Cool :)
Two things:
* please add the new supported platforms to the TSCH readme (several locations within the file)
* regarding the node-id problem in rpl-tsch, I'm not particularly keen on keeping it as it is. We could for instance replace it with a hardcoded coordinator address, set by default to the MAC address of node 1 in Cooja for z1 nodes (because this is what is used for the regression tests)

**Comment by alignan** [comment]
Great contrib! I thought this was already included in the previous CC2538/TSCH commit, so great to have :smile:

**Comment by sumanpanchal** [comment]
@simonduq @alignan 
I have done all the necessary changes as per your suggestion.

**Comment by alignan** [comment]
:+1: from me, @simonduq?

**Comment by simonduq** [comment]
:+1:

**Comment by sumanpanchal** [comment]
Thanks @simonduq and @alignan :)

**Pull request merged**
