### PR TITLE
Minor fixes for the WisMote platform

### PR DESCRIPTION
**Pull request by nvt**
This PR changes the WisMote's default MAC and RDC layers to CSMA and ContikiMAC, respectively. Furthermore, it fixes a compilation error concerning an invalid header inclusion when the IPv4 stack is enabled.

### CODE REVIEW

**Comment by simonduq** [comment]
:+1:

**Comment by sumanpanchal** [comment]
+1

**Comment by cmorty** [comment]
What about a compilation test-case? (There should be more of those!)

**Comment by nvt** [comment]
Yes, good test cases are welcome contributions.

**Pull request merged**
