### PR TITLE
Avoiding conditional directives that split up parts of statements.

### PR DESCRIPTION
**Pull request by lzmths**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

```
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
```

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by vsaw** [comment]
I like the sentiment of the pull request! :+1: 
For the fail I think it's because of the use of `stdbool` in `resolv.h` ([Been there myself :wink:](https://github.com/tadodotcom/contiki/pull/1))

**Comment by cmorty** [comment]
My guts tell me that is would be a good idea to define the bool within the ifdef. Otherwise it's possible to remove the else branch without getting an error.

**Comment by simonduq** [comment]
@lzmths are you intending to try and fix the compilation problem?
Closing after timeout otherwise

**Comment by simonduq** [comment]
closing after timeout

**Pull request closed without merging**
