### PR TITLE
Travis: compile er-rest-example for the Wismote platform rather than Sky

### PR DESCRIPTION
**Pull request by simonduq**
Because we don't want to restrain ourselves with 700 bytes of new features!

### CODE REVIEW

**Comment by cmorty** [comment]
Isn't being able to run more features without the need of more powerful hardware one of the awesome developments in the WSN domain? Yet more serious: What about a full version and a reduced example for sky? After all it is still one of the most popular platforms.

**Comment by simonduq** [comment]
We still have plenty of examples compiled for Sky, enough IMO. The platform is more than 10 years old, I'd rather move on than be stuck on the magic number "48k".

**Comment by g-oikonomou** [comment]
:+1:

**Comment by nvt** [comment]
:+1:

**Pull request merged**
