### PR TITLE
Various Orchestra fixes

### PR DESCRIPTION
**Pull request by simonduq**
This PR includes a number of fixes to Orchestra, including a fix to https://github.com/contiki-os/contiki/issues/1671

### CODE REVIEW

**Comment by yatch** [comment]
Is there any possibility that [new_time_source()](https://github.com/simonduq/contiki/blob/c7694e4dbdcfe831b29d8128f3845d9a9806ceac/apps/orchestra/orchestra-rule-eb-per-time-source.c#L75) in `orchestra-rule-eb-per-time-source.c` has NULL for `old` or `new`? If it is the case, I think it would be better to add NULL checks there. Here is an example:

```C
uint16_t old_ts = old != NULL ? get_node_timeslot(&old->addr) : 0xffff
uint16_t new_ts = new != NULL ? get_node_timeslot(&new->addr) : 0xffff
```

**Comment by simonduq** [comment]
Good point, will fix

**Comment by simonduq** [comment]
(or feel free to PR on my branch, your suggested fix is exactly what we need)

**Comment by yatch** [comment]
@simonduq OK, I'll send a PR later :-)

**Comment by simonduq** [comment]
:+1:

**Pull request merged**
