### PR TITLE
Update port.h

### PR DESCRIPTION
**Pull request by Simpleyyt**
Fix a bug.

### CODE REVIEW

**Comment by tonnenpinguin** [comment]
Without having looked into the code that uses these macros:
Wouldn't a do{...}while(0) wrapper be appropriate?

**Comment by Simpleyyt** [comment]
when the code without
PORT_CLEAR_X(port,pin) PORT_CLEAR_X(port,pin)
expand, it will be
do {...} whie(0)  do {...} while(0)
syntax error for c.

在2015年11月5，下午 9:55，Berni <notifications@github.com> 
写道：

**Comment by msloth** [comment]
Without being too familiar with this specific file and what it does, it rather seems the bug is whoever wrote those lines accidently wrote `PORT_CLEAR_X()` twice. Is that necessary? Especially on the `TOGGLE` it will (should) just toggle back and forth, not what you would expect.

**Comment by g-oikonomou** [comment]
Yes I think the original was an accidental additional paste.

**Comment by Simpleyyt** [comment]
I agree.

在2015年11月5，下午 10:32，George Oikonomou 
<notifications@github.com> 写道：

**Pull request closed without merging**
