### PR TITLE
Wismote external flash driver

### PR DESCRIPTION
**Pull request by sumanpanchal**
Contiki 2.7 does not have driver support for WISMOTE external flash. I have updated the driver of external flash for WISMOTE platform.

### CODE REVIEW

**Comment by nvt** [comment]
Wismote external flash support is a welcome addition, but I suggest a couple of minor changes.

* Squash the seven commits into one, or possibly two commits.
* Remove the commented SPI_FLASH_ENABLE and SPI_FLASH_DISABLE macros that were used previously.

I'll test the driver on a Wismote, and possibly port Coffee to it if it works well.

**Comment by sumanpanchal** [comment]
@nvt 
- Squashed all the commits into one.
- Removed the commented SPI_FLASH_ENABLE and SPI_FLASH_DISABLE macros.
- Tested with CFS using test-coffee.c example.

**Comment by nvt** [comment]
Could you rebase and push -f? I still see several commits, including a "Merge branch" commit.

**Comment by sumanpanchal** [comment]
I have squashed all the commits into one. Is it ok now?

**Comment by sumanpanchal** [comment]
@nvt 
Did you try external memory driver on a WISMOTE with Coffee file system?

**Comment by sumanpanchal** [comment]
Maintainers,
Let me know is there anything to be done in this PR to make it suitable for merge in Contiki master branch.

**Comment by sumanpanchal** [comment]
Maintainers,
Let me know is there anything to be done in this PR to make it suitable for merge in Contiki master branch.

**Comment by sumanpanchal** [comment]
Its almost 2 months I have submitted this PR and did not get any feedback from maintainers. 
Can some maintainer look into this PR to make it suitable for merge in Contiki.

**Comment by alignan** [comment]
I don't have a wismote to test, @nvt?

**Comment by nvt** [comment]
The PR is in the processing queue -- feedback will be provided whenever the testing has been completed.

**Comment by sumanpanchal** [comment]
Thanks for the update.

**Comment by nvt** [comment]
I have at last tested this driver with Coffee on a Wismote, and it gave the correct results. Before merging, however, I suggest that the author of the original driver for the STM25P80 should be added in the file since the changes are not that large.

**Comment by sumanpanchal** [comment]
@nvt 
Thanks for the feedback. I have added the author name as per your suggestion.

**Comment by nvt** [comment]
:+1:

**Comment by sumanpanchal** [comment]
@nvt Thanks a lot :)

**Pull request merged**
