### PR TITLE
Use RPL_DAG_LIFETIME when computing dag lifetime

### PR DESCRIPTION
**Pull request by laurentderu**
When updating the dag lifetime, the multiplication constant RPL_DAG_LIFETIME must be used (or it has no use at all :) )

### CODE REVIEW

**Comment by alignan** [comment]
:+1:

**Comment by laurentderu** [comment]
Forgot to update the event timing in the non-regression test related to multi dag, if the lifetime is multiplied by 3 so must be the test...

**Comment by nvt** [comment]
:+1:

**Comment by arurke** [comment]
I'll just add a related comment/question here on the DAG lifetime (which is also related to #912 by @laurentderu ).

I noticed during testing that a node never leaves a DAG due to DAG lifetime. The function which has a chance to do this is rpl_purge_dags(), added in #912, however it requires the "joined" flag to be 0, which can only happen if the node has switched to an alternative DAG (or has become root itself). Hence a node will forever be joined to the single DAG even if its lifetime is expired.

Now, this might not necessarily be unintended or bad behavior. The only effect I can think of is that this blocks the node from sending DIS messages in search for a new DAG, however glancing at the RFC I cannot see any req. for this to actually happen either.

**Pull request merged**
