### PR TITLE
Live Traffic Capture and Sniffer for cc2420 

### PR DESCRIPTION
**Pull request by warner83**
Implemented Live Traffic Capture and Sniffer for cc2420 based on the
original sensniff project (https://github.com/g-oikonomou/sensniff).
    
See http://www.iet.unipi.it/c.vallati/z1_sniffer.shtml

### CODE REVIEW

**Comment by alignan** [comment]
Nice :-)

I have been using this since last year when we last chat about it (see https://github.com/alignan/contiki/commit/db6cb64e147fd61e9f9cfa4f68c666a0c01af88c), however after talking with @g-oikonomou about this at the time, I think the right way would be to try and have a generic sniffer application rather than one for each platform.

Also I think it would be best to add the `sensniff` as submodule rather than copying the application.

**Comment by g-oikonomou** [comment]
A generic sniffer application would be pure great. I had some discussions a long time ago, but I just never got round to it.

Meanwhile, I definitely agree that there is no place for the sensniff script itself in the example folder. We may or may not ship it as a submodule under tools at some point, but that's a different story.

**Comment by g-oikonomou** [comment]
@warner83 this PR cannot be merged as-is, mainly due to comments above. Are you willing/do you have time to address comments?

**Comment by warner83** [comment]
@g-oikonomou @alignan I definitely agree that a generic sniffer application would be the best solution. I also agree that the sensniff tool should be place somewhere else (truth to be told I pushed it by mistake :) ).  
I will try to rework the PR to generalize its structure!

**Comment by simonduq** [comment]
Hey,
This timed out a while ago.
@warner83 is that still on your list?

**Comment by warner83** [comment]
Hi @simonduq it is still in my list, unfortunately, I didn't have time so far!

**Pull request closed without merging**
