### PR TITLE
Cortex-M and CC2538 multi-threading

### PR DESCRIPTION
**Pull request by bthebaudeau**
This PR:
- updates CMSIS-CORE,
- switches the CC2538 code base to CMSIS-CORE,
- fixes a few things in `core/sys/mt`,
- adds a common Cortex-M `mtarch` implementation,
- enables the Cortex-M `mtarch` implementation on CC2538.

See the commit messages and the documentation in the code for more details.

### CODE REVIEW

**Comment by g-oikonomou** [comment]
👍 Not a lot to say here :)

Suggest additional pair of eyes to look at changes in core before merging this.

**Comment by alignan** [comment]
The code seems OK, it has took me quite a while and probably understood half of it, great stuff!

:+1:

**Comment by bthebaudeau** [comment]
Thanks for your reviews. This PR has been inactive for more than two months. Any core reviewer willing to comment? "I approve this PR. If nobody disapproves within one month, I will merge it."

I will send an update to fix the conflicts caused by the changes made to the master branch since this PR.

**Comment by g-oikonomou** [comment]
I'm taking your word for it 👍

**Comment by alignan** [comment]
Rebase and merge, ACK and go :smile:

**Comment by bthebaudeau** [comment]
Final timeout. Merging.

**Pull request merged**
