### PR TITLE
cc2538dk: Add Coffee filesystem example

### PR DESCRIPTION
**Pull request by bthebaudeau**
Add the Coffee filesystem example from the Wiki as suggested by @alignan in #1162.

### CODE REVIEW

**Comment by alignan** [comment]
After merging #1162 I noticed there is an existing [CFS example](https://github.com/contiki-os/contiki/blob/master/examples/sky/example-coffee.c) for the `sky` platform.  I think it would be better to have a single coffee example for "most" platforms, in the same fashion we moved the `rssi-scanner` to avoid code repetition.

I also have been thinking about creating a `cc2538` example directory, and move examples like the `mqtt`, `pwm`, etc., to this location instead.  At least for users it would be less confusing having to search i.e for `remote` examples while working with the `cc2538dk`, `openmote`, etc, and generally it would improve the cc2538 support.

**Comment by bthebaudeau** [comment]
Do you think that it would be worth explicitly formatting the filesystem at the beginning of this example rather than to rely on the flash erase when programming the example?

> After merging #1162 I noticed there is an existing CFS example for the `sky` platform.

Yes, and for several other platforms too.

> I think it would be better to have a single coffee example for "most" platforms, in the same fashion we moved the `rssi-scanner` to avoid code repetition.

Yes, that would be great, but:
 - How would you merge all the existing examples, some of which seem to have some specifics?
 - How would you ensure that this common example is automatically built (Travis...) and tested for all the platforms supporting it?
 - How would users know where to find this common example and that it is supported by a given platform?

Some additional Makefile settings and documentation would probably do.

> I also have been thinking about creating a `cc2538` example directory, and move examples like the `mqtt`, `pwm`, etc., to this location instead. At least for users it would be less confusing having to search i.e for `remote` examples while working with the `cc2538dk`, `openmote`, etc, and generally it would improve the cc2538 support.

I agree, but here too, we have to find a way of at least documenting and automatically building these common examples for all the supported platforms, `cc2538dk` being the default.

**Comment by alignan** [comment]
I was thinking on something like [this](https://github.com/alignan/contiki/tree/pull/cfs-example-unified), what do you think?

**Comment by nvt** [comment]
@alignan I agree that the examples and tests should be placed in a new directory. It's been a long time since the Sky was the only platform with support for Coffee.

**Comment by bthebaudeau** [comment]
@alignan I have not tested your suggestion, but it looks great.

Besides my comments on the diff, my `project-conf.h` is missing for the `cc2538` targets. Without it, the examples would not run properly on these platforms. Some conditional mechanism has to be created here, as discussed in #1447, e.g. a `TARGET_<TARGET_NAME>` or `SOC_<SOC_NAME>` C preprocessor definition that could be automatically generated by `Makefile.include` from the make variables.

**Comment by bthebaudeau** [comment]
Some function pointers suggested by @g-oikonomou in #1447 could not fix this issue, but they could help if something else needs to be adjusted for a given platform.

**Comment by g-oikonomou** [comment]
Makefile.include generates this: `-DCONTIKI_TARGET_$(TARGET_UPPERCASE)=1`. Are you referring to something different?

**Comment by bthebaudeau** [comment]
This definition can do the trick. I did not know it, but this is exactly the kind of definition that I was suggesting. But here, we would have to:
```
#if CONTIKI_TARGET_CC2538DK || CONTIKI_TARGET_ZOUL
#define ...
#endif
```
while a CPU or SoC definition would simplify things to:
```
#if CONTIKI_CPU_CC2538
#define ...
#endif
```

But `CONTIKI_TARGET_<TARGET_NAME>` is just fine enough for now.

**Comment by Devesh24** [comment]
Hello Guys,
                       After flashing coffee example there is nothing coming on UART, any idea ?

**Comment by alignan** [comment]
Should we close this in favour of #1490 ?

**Comment by bthebaudeau** [comment]
Superseded by #1490.

**Pull request closed without merging**
