### PR TITLE
Unified CFS/Coffee examples

### PR DESCRIPTION
**Pull request by bthebaudeau**
This PR aims at providing common CFS and Coffee examples for all the platforms supporting Coffee.

The examples are moved from sky to a common cfs-coffee example folder.

This PR supersedes #1490.

### CODE REVIEW

**Comment by bthebaudeau** [comment]
Travis fails because:
 - the tests do not build for avr-raven (unimplemented CFS API: probably missing setting to enable it),
 - test-coffee times out on sky + Cooja (it takes between 70 and 80 s on Firefly, so maybe the timeout should just be increased for sky, especially given the fact that the test fixes make it run longer).

I'll look into it.

@alignan In the README, you say that the examples do not build for sky because of a ROM overflow, but test-coffee actually builds fine with Travis, so are you referring to test-cfs or example-coffee, or is this comment no longer valid?

**Comment by alignan** [comment]
This comment is no longer valid

**Comment by alignan** [comment]
Everything is working for the Zoul/RE-mote :+1:

**Comment by nvt** [comment]
Nice work! Increasing the timeout for the Sky test should be fine; the test took 159 seconds when running it in MSPsim.

**Comment by bthebaudeau** [comment]
Fixed.

I've also:
 - removed from the README the obsolete note about the ROM overflow for sky,
 - added to the README a note about the file system overflow for some of the examples for avr-raven,
 - added the build of `cfs-coffee/sky` to the regression tests.

Hopefully, Travis should now pass, though it has just failed in `21-large-rpl` because of a simulation timeout, which seems completely unrelated. Perhaps it's just because Travis lags from time to time. I've just restarted it.

**Comment by alignan** [comment]
Please also include the `openmote` as well, is another `cc2538-based` platform.

**Comment by bthebaudeau** [comment]
Done.

**Comment by bthebaudeau** [comment]
The first run of Travis timed out again in `21-large-rpl`:
https://travis-ci.org/contiki-os/contiki/builds/134265866

Then I restarted the build, and the request has been accepted and the build created, but it does not start, even after several hours:
https://travis-ci.org/contiki-os/contiki/builds/134274432
https://travis-ci.org/contiki-os/contiki/builds/134305034
https://travis-ci.org/contiki-os/contiki/requests

**Comment by nvt** [comment]
I restarted the Travis tests now; let's hope for better luck this time.

**Comment by bthebaudeau** [comment]
@nvt Thanks. It has now passed.

@alignan You can now merge if this is OK for you.

**Comment by alignan** [comment]
My pleasure :+1:

**Pull request merged**
