### PR TITLE
cc2538: Add crypto drivers and examples for AES-CCM and SHA-256

### PR DESCRIPTION
**Pull request by bthebaudeau**
Signed-off-by: Benoît Thébaudeau <benoit.thebaudeau@advansee.com>

### CODE REVIEW

**Comment by alignan** [comment]
I will test it over the weekend, this is a most welcome contribution :-)

**Comment by drandreas** [comment]
@alignan great news! I have drivers for ECC laying around since late 2014. They build upon this pull request. Hence, my extensions are waiting for this one to be accepted.

**Comment by bthebaudeau** [comment]
@alignan Thanks! Great news! After one year and a half, I had lost hope to see it merged one day.

I see that I now have to rebase it. I'll try to do that before the weekend.

**Comment by bthebaudeau** [comment]
Moved to #1071.

**Comment by hakanay** [comment]
Sorry !.  Can anyone help me ?. I am new  about contiki os. So I cant security my homework.
how can I use hardware Aes implementation to cc2420?.  Can anyone send me code examples implementation hardware Security Aes to contiki...

**Pull request closed without merging**
