### PR TITLE
cc26xx-cc13xx: Add iBeacon support

### PR DESCRIPTION
**Pull request by cquijano**
This commit add support for [iBeacons](https://en.wikipedia.org/wiki/IBeacon)

To enable it, you must define:
```
#define IBEACON_CONF_ENABLED     1
#define IBEACON_CONF_UUID { 0xF0, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFB, 0xFC, 0xFD, 0xFE, 0xFF }
```
Of course with a valid UUID.

### CODE REVIEW

**Comment by g-oikonomou** [comment]
I thought support for iBeacons required royalties paid to Apple. Has this changed?

**Comment by adamdunkels** [comment]
Apple are being Apple:y about everything, including the iBeacon brand. It is possible to send BLE beacons with a format that matches that of Apple's iBeacons, but who knows what Apple will do if you do. In any case, iBeacons haven't really picket up much traction. There are alternative BLE beacon formats that aren't as locked down as Apple's, such as @scottjenson's Eddystone format (https://github.com/google/eddystone).

**Comment by scottjenson** [comment]
Please let me know what you were trying to do with iBeacon support and if it makes sense to add Physical Web support as well. I can see how broadcasting and receiving Eddystone-URL packets with Contiki could be useful. We have lots of sample implementations over at our [repo](https://github.com/google/eddystone)

**Comment by cquijano** [comment]
You can ignore this pull request, I added support for Eddystone-UID beacons on new pull request https://github.com/contiki-os/contiki/pull/1921

**Comment by scottjenson** [comment]
Any reason you didn't add Eddystone-URL while you were at it? It's no more work.

**Comment by cquijano** [comment]
At this point, I only need the Eddystone-UID Beacon for our application. I know that have Eddystone-URL could be interesting if I have time I will  do it.

**Comment by cquijano** [comment]
At this point, I only need the Eddystone-UID Beacon for our application. I know that have Eddystone-URL could be interesting if I have time I will  do it.

**Comment by g-oikonomou** [comment]
I'm closing this

#1921

**Pull request closed without merging**
