### PR TITLE
oma-lwm2m: Add JSON writer

### PR DESCRIPTION
**Pull request by gebart**
A minimal JSON writer for LWM2M resources.

Depends on #1652, ~~#1651~~

### CODE REVIEW

**Comment by joakimeriksson** [comment]
Did you test with Leshan or Wakaama? I think it looks good - nice to see progress on the LWM2M codebase.

**Comment by gebart** [comment]
@joakimeriksson I used Copper for testing the service response. The Leshan server is still using OMA TLV formatted responses with this PR.

**Comment by nfi** [comment]
http://www.gnu.org/software/libc/manual/html_node/Formatted-Output-Functions.html

**Comment by gebart** [comment]
The reason for the greater than rather than greater than or equal is that the CoAP response payload will not contain the trailing null byte and uses the length of the response to determine which bytes to copy, so no trailing null byte is necessary here.

**Comment by nfi** [comment]
I aggree that the trailing null byte should not be necessary here but the problem is that different implementations of `snprintf()` handles this differently. Modern implementations tend to always add the trailing null byte, discarding the last "real" byte if needed.

Example compiled with gcc:
>   static char buf[5];
>   int ret = snprintf(buf, 4, "abcd");
>   printf("ret=%d s='%s'\n", ret, but);

> => ret=4 s='abc'

**Comment by gebart** [comment]
@nfi Yes, you are correct, the output may have been corrupted if the buffer is filled since the last letter may have been replaced by a null byte.

**Comment by gebart** [comment]
Corrected the output length checks.
OK to squash?

**Comment by nfi** [comment]
Thanks for the update. I think this looks good and is ready to squash, but please remove the extra space after `if` (code style).

**Comment by gebart** [comment]
rebased, squashed. #1652 should be reviewed and merged before merging this.

**Comment by alignan** [comment]
#1652 has been merged already, restarting the travis job.

**Comment by nvt** [comment]
:+1:

**Pull request merged**
