### PR TITLE
Change the default IPv6 prefix from aaaa::/64 to fd00::/64

### PR DESCRIPTION
**Pull request by simonduq**
This PR brings https://github.com/contiki-os/contiki/pull/712 back to life, now with `fd00` rather than `fc00`. As mentioned [here](https://github.com/contiki-os/contiki/pull/712#issuecomment-137351534) I (and some others) believe `fd00` to be a better alternative than the Sixxs prefix.

### CODE REVIEW

**Comment by joakimeriksson** [comment]
This should just go in! It is much better than the aaaa:: prefix as we always have been using! :+1:

**Comment by alignan** [comment]
:+1: after resolving conflicts

**Comment by simonduq** [comment]
rebased, conflict resolved, thanks!

**Comment by joakimeriksson** [comment]
Why is this not just getting in? :+1: from me again! We need to get rid of aaaa:: and have something that is a valid address for the default (local-global) prefix which fd00:: is!

**Comment by simonduq** [comment]
Rebased again, conflicts solved. This is going to affect many external examples / tutorials etc, so I'd like to see some extra support before merging.
@laurentderu, any thoughts from a 6LBR point of view?
@adamdunkels @g-oikonomou?

**Comment by g-oikonomou** [comment]
Certainly better than `aaaa::`! :+1:

**Comment by laurentderu** [comment]
For 6lbr, I think there will be a surge in support request but no real issues . The network prefixes are either user configurable or auto-configured, and the non regression tests are already using different prefixes, so everything should be fine.

**Comment by simonduq** [comment]
merging, then!

**Pull request merged**
