### PR TITLE
Fix log messages of Travis tests in 12-rpl

### PR DESCRIPTION
**Pull request by simonduq**
This PR fixes the output of RPL-related regression tests. Should have no other effect on the tests.

### CODE REVIEW

**Comment by adamdunkels** [comment]
I was about to say :+1: to this since this looks good and travis was very green and happy, but then I wanted to see the new output and looked at the travis log.

To my horror the log says that the RPL test fails, but travis gives it a green light anyway!

https://travis-ci.org/contiki-os/contiki/jobs/61989649

No idea what the problem is, but there is something in there that looks like an error:
`xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option`
Maybe that has something to do with this?

In any case, this is pretty serious as it makes us merge code that doesn't pass the travis tests.

**Comment by simonduq** [comment]
Ooops...
Good (and important!) catch :)
No idea what this can be, I'll look into this.

**Comment by simonduq** [comment]
Found out! It's expected behavior since this commit https://github.com/contiki-os/contiki/commit/74b741bad20397c2bcbe59abe9ba96f956cc9b2d. The first test with seed 1 fails, then we have a new run with seed 5 which succeeds, and the conclusion if one seed works then the test passes. Seems like a bad idea to me, I'd suggest to regard any failure as global failure.

Now, looking at the recent history, it seems the failure on first seed for this particular root loss test came with my RPL probing https://github.com/contiki-os/contiki/pull/1053. I did struggle with getting probing to pass the root loss test, but of course did not notice there was a Travis failure left; sorry about that.

What was the root loss test originally intended for? It is called "temporary root loss" but the test ends before the root is back. I don't think continued traffic without a border router is really wanted -- and probing does help figuring our the root is gone quicker, resulting in nodes leaving the network and test failing. I suggest to either remove or fix the test so that is lasts long enough to see the root back (but then, not sure what condition to use for success).

**Comment by simonduq** [comment]
Added a commit that modifies the root loss test -- thoughts are welcome!

**Comment by g-oikonomou** [comment]
Related to #980 ?

**Comment by simonduq** [comment]
@g-oikonomou I don't think so. However, #980 might be fixed by https://github.com/contiki-os/contiki/pull/1050. The problem addressed in the latter pull was occasional memcmp at NULL, causing Cooja nodes to segault. The symptoms were exactly the same as in #980: simulation stopping before 100% and Cooja attempting to issue a core dump (failed attempt in Travis, but can work on local setups). Might be worth rebasing the code in #980 to rerun Travis and see if the problem persists.

**Comment by nvt** [comment]
:+1:

**Pull request merged**
