### PR TITLE
Remove Deluge and associated test files.

### PR DESCRIPTION
**Pull request by nvt**
This Deluge implementation was created in 2007 for research paper experiments with ELF module distribution. It has not been used much since then, and the prevalent method of updating software in real IoT products today is full firmware updates that are typically transferred with more reliable bulk transfer protocols. Anyone interested in using it can of course still access it from the repository history and previous Contiki releases.

### CODE REVIEW

**Comment by simonduq** [comment]
:+1: 
(don't hesitate to remove even more unused features btw :))

**Comment by alignan** [comment]
Should this be documented elsewhere? I would suggest mentioning this on the wiki as done with the lost platforms.

**Comment by simonduq** [comment]
good idea :)

**Comment by nvt** [comment]
OK, I'm merging this and creating a Wiki page about lost modules.

**Comment by nvt** [comment]
The new page on lost modules can be found here: https://github.com/contiki-os/contiki/wiki/Lost-modules

**Comment by alignan** [comment]
Thanks!

**Pull request merged**
