### PR TITLE
Added mc1322x functions

### PR DESCRIPTION
**Pull request by SmallLars**
Learned from pull request #594. Added some new functions for hardware usage on mc1322x.

### CODE REVIEW

**Comment by simonduq** [comment]
I don't know the platform so all I can say is the code style is off, and this adds new functions which are not documented (also look unused). As this did not raise interest from the community and has been idle for so long, I'll close in one month unless someone wants to defend this PR.
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by SmallLars** [comment]
Documentation:
soft_reset: Page 64: https://github.com/SmallLars/ba-codtls/raw/master/dokumente/MC1322xRM.pdf
nvm_verify: Page 34: https://github.com/SmallLars/ba-codtls/raw/master/dokumente/MC1322xDRVRRM.pdf
clock_set_seconds: sys/clock.h

When i have added the code, i used same code style as i found in the original file.
You want me to change the code style of the whole file and add comments to all functions?
Maybe @malvira can check too?

**Comment by simonduq** [comment]
Thanks for your reply. In general if you want your PR to get attention it's a good idea to include a description of what your are addressing, in order to convey why this is important or useful. We have currently many PRs open, it is difficult to stand out.

Comments explaining the new features, in the code, would be nice to have yes. As for code style, what I noticed is:
* indent: should be 2 white spaces rather than 1 tab
* functions/variable names: should use underscores rather than capitals, e.g. `num_bytes` rather than `numBytes`.

That being said, I realize only now that the whole file already uses tabs and wrong naming, so just forgot about this. Sorry for my earlier comment on code style.

I also hope we can get an opinion from @malvira on this PR before we make a decision!

**Comment by malvira** [comment]
Yes sorry about the code style! it is my fault and was written before I added the platform to Contiki (and even before I knew about Contiki ;) )  I'm pulling this. Has some overlap w/ #688. So suggest we start here and refactor #688 as necessary.

**Pull request merged**
