### PR TITLE
cc26xx ieee mode rf driver: fixes and features required for TSCH

### PR DESCRIPTION
**Pull request by casaroli**
these are features required by the TSCH port.

the (non-tsch) examples seem to still be working after these changes.

### CODE REVIEW

**Comment by alignan** [comment]
Does this conflicts with #1709 ?

**Comment by casaroli** [comment]
Yes. I saw the #1709 just after my PR. I guess it fixes all in #1710.

I did not drop it yet so I we can use for comparison.

I gonna test #1709 and then I drop my PR.

BR

**Comment by alignan** [comment]
Thanks! sorry for any inconvenience, and please comment!

**Comment by atiselsts** [comment]
Looks like amazing coincidence.

Thanks @casaroli - I saw two things in your pull request that I had missed:
1) avoiding setting packetbuf attributes while in interrupt context
2) expanding `RX_BUF_SIZE` by 4 bytes to make room for timestamp.

I took the liberty to update my PR with these changes.

**Comment by casaroli** [comment]
Hello Atis,

I am glad it helped somehow!

BR

**Pull request closed without merging**
