### PR TITLE
added driver for AES acceleration engine on the CC253x

### PR DESCRIPTION
**Pull request by phoenix-frozen**

### CODE REVIEW

**Comment by phoenix-frozen** [comment]
Hi all. Any chance of this being pulled?

**Comment by phoenix-frozen** [comment]
Hi guys, this has been inactive for a couple of months. Any chance of it being pulled?

**Comment by simonduq** [comment]
This is surely a welcome feature, but as a non-user of this platform all I can say now is the code style doesn't match Contiki's required formatting (from a quick look, at least: indent, inline comments): https://github.com/contiki-os/contiki/wiki/Code-Contributions#code-formatting

Please fix this and rebase.

**Comment by phoenix-frozen** [comment]
Closing because I don't really have time to work on this right now. Will reopen once I've done the requested fixes.

**Pull request closed without merging**
