### PR TITLE
RFID for Z1 platform

### PR DESCRIPTION
**Pull request by minecet**
This pull request introduces a new driver for NXP MFRC522 Contacless RFID Reader for the Z1 platform.

### CODE REVIEW

**Comment by alignan** [comment]
Nice!

Please run uncrustify, the code style needs some lovin'

https://github.com/contiki-os/contiki/wiki/Code-Contributions#code-formatting

**Comment by msloth** [comment]
Cool stuff adding RFID, and if I'm not mistaken this particular RFID reader is highly integrated, meaning there's no need to get knee-deep in the ISO14443/15693 (etc) this and that, making it quick and simple to add RFID-reading capabilities to a device :)

There's a file in the apps folder that contains `AUTOSTART_PROCESSES`, I'm guessing that's not intended since that's not what's expected from a driver. Instead, you'd want sth like `mfrc522_init()` which starts the RFID reader process. That file also got the wrong line endings (you can run eg `d2u yourfile.c`) - see the diff to see what I mean. Further, the filename case is not following the style.

Finally I don't think adding `apps/` here is good (platform/CPU-specific). I'd instead suggest adding an example file in the appropriate folder to show how to use it.

**Comment by minecet** [comment]
Hi,
I made the changes that you have mentioned. Hopefully, I haven't missed anything. Please let me know if you have any further comments. Could you have a look again? 
Thanks!

**Comment by jdede** [comment]
What is the status of this piece of code? What shall we do to get it merged into Contiki? @alignan @msloth, do you have any recommendations and ideas?

**Pull request closed without merging**
