### PR TITLE
TSCH + Basic 6TiSCH

### PR DESCRIPTION
**Pull request by simonduq**
TSCH (TImeSlotted Channel Hopping) is a MAC layer of the [IEEE 802.15.4e-2012 amendment](http://standards.ieee.org/getieee802/download/802.15.4e-2012.pdf), currently being integrated as part of the new IEEE 802.15.4-2015. [6TiSCH](https://datatracker.ietf.org/wg/6tisch/documents/) is an IETF Working Group focused on IPv6 over TSCH. This is a Contiki implementation of TSCH and the 6TiSCH so-called "minimal configuration", which defines how to run a basic RPL+TSCH network. 

We provide a full documentation of the features, code structure, how to use, configure and port it to new platforms in this [README.md](https://github.com/simonduq/contiki/blob/pr/tsch/core/net/mac/tsch/README.md).

Among the key features (full list [here](https://github.com/simonduq/contiki/blob/pr/tsch/core/net/mac/tsch/README.md#features)), we include standard 6TiSCH link-layer security (based on Contiki's ccm-star interface), standard 6TiSCH interfacing of TSCH with RPL, and a generic scheduling API for TSCH. We also include [Orchestra](https://github.com/simonduq/contiki/blob/pr/tsch/apps/orchestra/README.md), an autonomous scheduling solution where nodes maintain their own schedule locally, solely based on their local RPL state.

This implementation participated in the ETSI 6TiSCH plugtest, where it interoperated successfully with all 4 implementations it was tested against, including OpenWSN, a reference implementation of 6TiSCH.

The code is ported to jn516x, sky and z1. It was extensively evaluated in two different testbeds (25 jn5168 nodes, 98 sky nodes) along with RPL in storing mode, achieving end-to-end delivery ratios over 99.99% (less than one loss per 10k). For a detailed evaluation, see our paper [*Orchestra: Robust Mesh Networks Through Autonomously Scheduled TSCH*](http://www.simonduquennoy.net/papers/duquennoy15orchestra.pdf), ACM SenSys'15.

This PR includes regression testing in Cooja with emulated z1 nodes, checking that a RPL/TSCH network builds correctly. The test is run with and without security, and with either 6TiSCH minimal schedule or Orchestra.

Our working repository (code maximum a few commits ahead of this PR) is [EIT-ICT-RICH](https://github.com/EIT-ICT-RICH/contiki).

### CODE REVIEW

**Comment by adamdunkels** [comment]
Great work @simonduq! A massive pull request that will probably take some time to go through. Took a quick look at the paper (interesting to see that good old ContikiMAC still performs pretty well in comparison!) but didn't read through so maybe my questions are answered there. I see that the paper says that this is able to support non-deterministic traffic, but is it right to assume that this is still mostly intended for node-to-root traffic with fairly stable traffic patterns? Or is it designed to work equally well with two-way traffic with more random patterns too?

**Comment by simonduq** [comment]
Orchestra is 100% designed for random access and any traffic pattern. Tested experimentally with request-response traffic originating from the root.

The basic idea is to run a set of over-provisioned slots repeating each with their own periodicity. Very much like asynchronous MAC layers, emulating always-on links, operating in an application-agnostic way.

The benefit is that we lower contention significantly compared to purely contention-based, and that we get channel hopping for free.

**Comment by simonduq** [comment]
Note that what I'm describing is only Orchestra. The PR is more general, it contains a generic TSCH and 6TiSCH, which can be used for any kind of scheduling, including more traditional centralized or distributed solutions. Most state-of-the-art solutions are, as you mention, for stable traffic patterns.

**Comment by adamdunkels** [comment]
Ok, cool! How does it handle packet bursts - do they go out back-to-back, or in separate slots (with time between them)?

**Comment by simonduq** [comment]
It's not great at handling bursts, you have wait for one period for every packet. I can think of possible enhancements for back-to-back transmission but that is not that trivial and not supported yet.

**Comment by simonduq** [comment]
Note: by standard, one slot is for only one packet (and its ack), so sending back-to-back would involve provisioning consecutive (conditional) slots for bursts and fragmented traffic. The maximum goodput is bounded by the slot duration, by default one packet per 10ms.

**Comment by simonduq** [comment]
So if you sum up, compared to ContikiMAC, this is worse for bursts, similar for latency-energy, and better for reliability, our primary goal (table 1 in the paper).

**Comment by sumanpanchal** [comment]
@simonduq 
I tried TSCH on Cooja using following scenario with z1 mote.
Node-1: rpl-tsch-border-router as a coordinator (aaaa::c30c:0:0:1)
Node-2: rpl-tsch-node as a node (aaaa::c30c:0:0:2)
Node-3: rpl-tsch-node as a node (aaaa::c30c:0:0:3)

Traffic: 
1000+ ping packets from the host to node-2.

Results:
First trial:
--- aaaa::c30c:0:0:2 ping statistics ---
1002 packets transmitted, 144 received, 85% packet loss, time 1001090ms
rtt min/avg/max/mdev = 147.480/246.285/841.126/119.720 ms

Second trial:
--- aaaa::c30c:0:0:2 ping statistics ---
1031 packets transmitted, 170 received, 83% packet loss, time 1030142ms
rtt min/avg/max/mdev = 143.205/261.104/1496.942/178.404 ms, pipe 2

Third trial:
--- aaaa::c30c:0:0:2 ping statistics ---
1005 packets transmitted, 143 received, 85% packet loss, time 1004114ms
rtt min/avg/max/mdev = 144.581/240.661/916.043/113.601 ms

tsch-screenshot

**Comment by simonduq** [comment]
Thanks for trying this out!

I need a bit more info from you:
* what is rpl-tsch-border-router? (no such thing in this PR)
* what ping packet size and period?
* is cooja running at 100% all the time like on the screenshot?
* what TSCH configuration are you using?

If you can share the exact code you're running (you can mail me) and your tunslip and ping commands so I can exactly reproduce your results, I'll be happy to troubleshoot this!

**Comment by sumanpanchal** [comment]
@simonduq 
1. rpl-tsch-border-router is the one you used in RICH project ./example/rich/rpl-border-router. I have done few modification in that code to make it works with ./example/ipv6/rpl-tsch.
2. ping packet size is 64 bytes and period is 1 second.
3. yes. cooja is running at 100% speed.
4. I am using default TSCH configuration what is given in this PR.
I am using tunslip6 which is there in your contiki-pr-tsch branch. 

Sure. will mail you the code.

**Comment by simonduq** [comment]
Ok I managed to reproduce this problem and found out the cause: this f2xxx DCO speed MSPSim bug, fixed in https://github.com/contiki-os/mspsim/pull/7. The bug is that there is a limit for the DCO speed set to 4.9 MHz, while z1 is configured for 8 MHz. The workaround I used so far for TSCH in Cooja (was not trying a border router in Cooja) is to set `F_CPU` to 3.9 MHz [here](https://github.com/simonduq/contiki/blob/pr/tsch/examples/ipv6/rpl-tsch/project-conf.h#L143). What I did not notice before: the MSPSim bug seems to make serial communication flaky. I tried the standard (non-tsch) border router and pinged it in single-hop and got lots of losses like you did.

After pulling https://github.com/contiki-os/mspsim/pull/7, recompiling MSPSim, and restoring the default 8 MHz speed for z1, I got ping to node-2 over TSCH to work nicely in Cooja:
```
--- aaaa::c30c:0:0:2 ping statistics ---
1000 packets transmitted, 991 received, 0% packet loss, time 999982ms
rtt min/avg/max/mdev = 137.874/261.099/6403.378/314.128 ms, pipe 7
```

That is, 9 losses per 1000, I guess to be attributed to the lack of serial flow control (TSCH did not report a single data packet drop, and I don't see why upper layers would have dropped).

**Comment by simonduq** [comment]
Now with https://github.com/contiki-os/mspsim/pull/7 and https://github.com/contiki-os/contiki/pull/1289 merged this should work out-of-the-box :) (make sure to update and recompile mspsim)

**Comment by sumanpanchal** [comment]
@simonduq 
Now I can able to ping node-1 from BR without any ping packet drop, after all necessary changes suggested by you.
```
--- aaaa::c30c:0:0:2 ping statistics ---
1000 packets transmitted, 991 received, 0% packet loss, time 999410ms
rtt min/avg/max/mdev = 138.639/249.558/2323.308/159.612 ms, pipe 3
```
But when I tried to ping node-2 from BR with same setup in Cooja, ping packets drop still persist.

First trial:
```
--- aaaa::c30c:0:0:3 ping statistics ---
1000 packets transmitted, 595 received, 40% packet loss, time 999047ms
rtt min/avg/max/mdev = 351.175/3159.066/36000.008/5724.241 ms, pipe 37
```
Second trial:
```
--- aaaa::c30c:0:0:3 ping statistics ---
1000 packets transmitted, 526 received, 47% packet loss, time 998978ms
rtt min/avg/max/mdev = 350.269/3045.051/32401.215/6000.735 ms, pipe 33
```
Third trial:
```
--- aaaa::c30c:0:0:3 ping statistics ---
1000 packets transmitted, 425 received, 57% packet loss, time 999210ms
rtt min/avg/max/mdev = 351.518/4540.313/39258.537/7425.697 ms, pipe 40
 ```

**Comment by simonduq** [comment]
Please share the code and csc files you're using, I'll be able to look into this next week.

**Comment by simonduq** [comment]
Meanwhile, you should try simply increasing the ping period. With 1s ping over two wireless hops, you might already reach the limits of the z1: this example reduces buffers quite drastically to fit TSCH on z1. With the default configuration which is purely contention-based, some more buffering would help. You might improve the situation by playing a bit with the configuration (e.g. more frequent wakeup, disabling fragmentation to free space for buffers), but on z1 you'll reach the limits pretty quick.

Note this stack is primarily aimed at newer 32bit platforms, z1 is mostly for emulation in Cooja and for regression testing.

**Comment by sumanpanchal** [comment]
Thanks for the feedback. I will look into it. Meanwhile I have mailed to the code with csc file to reproduce the results.

**Comment by simonduq** [comment]
OK, now getting good results on your example with improved configuration of rpl-tsch on z1 (more buffers, more frequent wakeup to reduce buffer load). Another problem was slight discrepancy in timing between real cc2420 and mspsim, now fixed by restoring the TSCH guard times as per 802.15.4e (the previous version was using tighter guards). Also rebase on latest. Got 998/1000 received pings, apparently serial losses (IPv6 complains about bad checksum or wrong version number on incoming SLIP frames every now and then).

**Comment by sumanpanchal** [comment]
Now I can able to ping NODE-1 from BR without any ping packets drop on real Z1 mote with DMA (#1336). 

Great work!! :+1: 

```
--- aaaa::c30c:0:0:9e ping statistics ---
1000 packets transmitted, 1000 received, 0% packet loss, time 999325ms
rtt min/avg/max/mdev = 87.665/274.238/5133.257/392.589 ms, pipe 6
```

**Comment by alignan** [comment]
@sumanpanchal cool! thanks for testing for the Z1 mote

**Comment by simonduq** [comment]
Hi Paolo,

> Is the RIME_SNIFFER the tool used as a network filter to classify the packets from different Orchestra Traffic Planes?

`RIME_SNIFFER` is only used to keep track of whether our parents have acknowledge our parent switch. What takes care of filtering is the `select_packet` provided by every Orchestra rule.

> Somewhere in the README, I read that TSCH could also be used with the RIME stack. In the paper, when you used the Static Centralised Scheduler did you use RIME and TSCH and somehow you determined a priori the static RIME routes to be used to forward the packets?

In the paper we only used IPv6, but for the centralized scheduler basically disabled RPL and set up static routes and schedules instead.

> Do you think you could include some basic example of RIME and TSCH to analyse some basic TSCH behaviour without taking into account RPL?

Good idea. Will definitely consider adding.

> Have you included all the RPL mechanisms created in the Paper's System Integration part? I saw months ago you included the probing mechanism if I am not wrong.

Probing is already upstream, that's correct (but without RSSI-based ETX initialization). The enhanced loop repair is on its way https://github.com/contiki-os/contiki/pull/1091. Not sure what to do with squared ETX, we could maybe add it as an optional feature of rpl-mrhof. FYI: the exact code used for the paper is available at https://github.com/simonduq/orchestra (already outdated of course, but does include the RPL tweaks)

> In any case, thanks for this and :+1: from me!

Thanks a lot for your interest and your suggestions!

**Comment by jonnteolsson** [comment]
Hi @simonduq, VERY nice piece of work! :+1: 

We are working on getting this running using our CC13xx and CC26xx platforms. At TI we believe it is very important that there are mature and well tested open source implementations of standards like TSCH available.

Keep up the good work, and we'll make sure to update you on our progress!

//Jonas, TI LPRF

**Comment by simonduq** [comment]
Thanks! Do not hesitate to ask if you have questions or need support. If you get this running before the PR is merged, feel free to contribute it to my repo https://github.com/simonduq/contiki/tree/pr/tsch (for inclusion in this PR)

**Comment by g-oikonomou** [comment]
Super :+1: for the feature, although I've not had a chance to test it yet. Colleagues and I want to test (and perhaps even deploy) this with the CC2650.

**Comment by simonduq** [comment]
Thanks @g-oikonomou, same goes here: I'll be happy to support!

**Comment by simonduq** [comment]
OK, as there is interest for the feature, may I ask other mergers to look at modified files only (i.e. ignore new files), and if 2 or more approve, we go ahead and merge? (the overall diff has only 134 "-" after all :))

Let me stress again that the feature was tested quite extensively and checked for inter-operability against OpenWSN and other implementations.

**Comment by alignan** [comment]
I wanted to test with the `Z1` mote as well but it has been already tested by @sumanpanchal and fixed issues, I will try to get this working with the `RE-Mote`  as well in a future PR.

:+1:

**Comment by simonduq** [comment]
OK that's probably enough :+1: for merging now. Will keep it open a little more for comments on core modifs, and then give it a go.

**Comment by nvt** [comment]
:+1:

**Comment by vuduccanh93** [comment]
@simonduq 
I have a problem with the config for 2 mechanism: Orchestra sender-base and Orchestra receivered-base.
I want to run an experiment only sender-base .and an experiment only receiverd-base.But I dont know config the same in where and how ?.
can you help me?
Thank you!

**Comment by lowji0** [comment]
Hi @simonduq  i need to implement Orechestra on contiki could you tell me how ! (Beginner on cooja)
any lesson  on cooja can be helped I want to modifirt into the code .c please Help ?

**Pull request merged**
