### PR TITLE
Change travis arm tests to use gcc-arm-embedded v5

### PR DESCRIPTION
**Pull request by g-oikonomou**
Do we want to switch travis to arm-gcc v5.2.1?

We'll first need to make sure that resulting binaries work well for the affected platforms.

If #1452 gets merged, then merging this one here will cause travis errors unless #1451 also gets merged.

### CODE REVIEW

**Comment by bthebaudeau** [comment]
> Do we want to switch travis to arm-gcc v5.2.1?

It is the current GCC ARM Embedded version, so yes, unless there is a very good reason not to. Some people are already beginning to use this version. Also, if people follow some `README`s like https://github.com/contiki-os/contiki/blob/master/platform/cc2538dk/README.md, they'll end up with this version.

> We'll first need to make sure that resulting binaries work well for the affected platforms.

Sure. I have already tested the build of all the CC2538 examples with this version on CC2538DK and Zoul. I have also runtime-tested a few CC2538 examples with this version, but not all.

**Comment by alignan** [comment]
I have tested V5 and works OK, but as you are updating travis, perhaps it would be worth to also update the `README.md` files of the `cc2538dk` and `zoul` platforms, and include instructions.

**Comment by g-oikonomou** [comment]
I have updated the respective READMEs as requested and I have tested srf06-cc26xx platform with v5 without any obvious problems.

Please consider.

**Comment by alignan** [comment]
:+1:

**Comment by bthebaudeau** [comment]
There is just a slight issue with the new READMEs vs. `.travis.yml`: the latest version provided by the PPA will very likely be upgraded in the future. If/when this happens, we won't be notified, and the READMEs will no longer match Travis tests. So either the version should not be indicated in the READMEs, or `.travis.yml` should pick up this specific version explicitly. Having a controlled infrastructure and informing users is better, so I prefer the latter, which can be implemented with something like `sudo apt-get -qq install gcc-arm-embedded=5-2015q4-1~wily1 srecord &&` (I don't know which version of Ubuntu is used by Travis, and perhaps it is not even controlled, which might be an issue here, but `wget` could then be used instead of `apt-get`).

**Comment by bthebaudeau** [comment]
According to the [documentation of Travis CI's build environment](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), Contiki uses Ubuntu 12.04 LTS Server Edition 64 bit, so the choices here for consistency between `.travis.yml` and the READMEs are:
 - make `.travis.yml` use `sudo apt-get -qq install gcc-arm-embedded=5-2015q4-1~precise1 srecord &&`,
 - change the READMEs to indicate that the reference used for testing is the latest version of the GNU ARM Embedded Toolchain.

@g-oikonomou @alignan What do you prefer (if you agree that something needs to be changed)?

**Comment by g-oikonomou** [comment]
We should probably force a version, lest travis decides to suddenly start failing due to an upgrade of the version provided in the PPA.

Changing a number of READMEs each time we bump to a new version is unnecessary PITA though, but I cannot think of a great solution. READMEs could simply state "Check travis.yml for the current version", but that would not be too friendly to the beginners (who are users that need READMEs the most)

**Pull request merged**
