### PR TITLE
Fixed the issue with CC2520_READ_REG macro to read correct value of register.

### PR DESCRIPTION
**Pull request by sumanpanchal**
Fixed the issue with CC2520_READ_REG macro to read correct value of register.

### CODE REVIEW

**Comment by sumanpanchal** [comment]
The following function belongs to CC2520 driver returns wrong value of register. It always returns 128. 
/*---------------------------------------------------------------------------*/
static uint8_t
getreg(uint16_t regname)
{
  uint8_t reg;
  CC2520_READ_REG(regname, reg);
  return reg;
}
/*----------------------------------------------------------------------------*/

The basic problem is with CC2520_READ_REG macro definition. After calling SPI_RXBUF before SPI_READ, it returns correct value of register.

**Comment by sumanpanchal** [comment]
Dear Maintainers,
Please provide your feedback on this PR.

**Comment by nvt** [comment]
The fix appears to make getreg return the correct values, but I don't think that a one-line change is substantial enough for inclusion in the author list.

**Comment by cmorty** [comment]
I wonder why such a severe bug wasn't caught earlier. Shouldn't it break basic functionality?

**Comment by sumanpanchal** [comment]
@nvt Thanks for the feedback. I have removed my name from author list.

**Comment by nvt** [comment]
:+1:

**Comment by sumanpanchal** [comment]
@nvt Thanks.

**Pull request merged**
