### PR TITLE
App/Tool/Example for usage of additional flash on econotag/mc1322x

### PR DESCRIPTION
**Pull request by SmallLars**
App/Tool/Example for usage of additional flash on econotag/mc1322x.
Depends on / Includes #685, so you are able to accept only new mc1322x functions.

### CODE REVIEW

**Comment by simonduq** [comment]
ok, same here, no interest from the community, will close in a month if nothing happens
(see [new PR merging policy](https://github.com/contiki-os/contiki/wiki/Code-Contributions#pull-request-merging-policy))

**Comment by simonduq** [comment]
@malvira ?

**Comment by malvira** [comment]
I like these changes and would like to see them get rebased and added. Sorry I was too busy to review when the PR was first made :(

I will try to rebase this unless someone else can get to it first.

**Comment by malvira** [comment]
has overlap with #685 (which has been merged). Rebasing should re-factor those changes out of this PR.

**Comment by SmallLars** [comment]
Rebase done :)

**Comment by malvira** [comment]
thanks @SmallLars ;)

**Pull request merged**
