### PR TITLE
 contiki-OTA with LAUNCHXL-CC1310

### PR DESCRIPTION
**Pull request by nehalrohit**
Hello,
I follow this link
https://marksolters.com/programming/2016/06/07/contiki-ota.html

here I m done  cd  /contiki/examples/cc26xx-cc13xx-ota-bootloader
change board (launchpad/cc1310) in Makefile .and  build with " make master hex" using uni-flash firmware.hex file download in cc1310. it run succesfully.
and  other terminal run OTA server as given below.

ipmsgclip_s_1568617465_0

 But I have some problem. 
ipmsgclip_s_1568617200_0

is it possible to OTA with LAUNCHXL-CC1310 ?

### CODE REVIEW

**Comment by KavinduS** [comment]
> Hello,
> I follow this link
> https://marksolters.com/programming/2016/06/07/contiki-ota.html
> 
> here I m done cd /contiki/examples/cc26xx-cc13xx-ota-bootloader
> change board (launchpad/cc1310) in Makefile .and build with " make master hex" using uni-flash firmware.hex file download in cc1310. it run succesfully.
> and other terminal run OTA server as given below.
> 
> ipmsgclip_s_1568617465_0
> 
> But I have some problem.
> ipmsgclip_s_1568617200_0
> 
> is it possible to OTA with LAUNCHXL-CC1310 ?

Hi rohith,
I am using cc2650. I am facing a simillar issue. How did you resolve it?
kavindu

**Comment by nehalrohit** [comment]
Hello kavindu,

For this issue you need one boarder router hardware. Build and run rpl-border-router code on your boarder router let say cc1310.
Build using **make TAREGT=srf06-cc26xx BOARD=launchpad/cc1310** command and upload it.
Run it using  **sudo ./../../../tools/tunslip6 -s /dev/ttyACM0 bbbb::1/64**
wait for connection of ota-bootloader to border router than it start accepting Co-AP requests.

**Comment by KavinduS** [comment]
HI ,
Thank you I resolved the issue, But after the download of the new firmware the lauchpad resets. After the reboot the new firmware does not work,

**Comment by nehalrohit** [comment]
Hello,
have you changed firmware version number? because downgrade version will not work.

**Comment by KavinduS** [comment]
Yes I changed it. Apparently I can’t access the external flash. Do you know
how to delete the content of the external flash?

**Comment by nehalrohit** [comment]
`**CLEAR_OTA_SLOTS=1` | Use this flag if you want the bootloader to erase all OTA slots in external flash before running any other code**.
try to this  make Bootloader.hex CLEAR_OTA_SLOTS=1

**Comment by KavinduS** [comment]
Hi Rohith,
I tried doing this, Did not work.

**Pull request closed without merging**
