### PR TITLE
Zolertia Orion ethernet router with active POE support

### PR DESCRIPTION
**Pull request by alignan**
This PR creates a new Zolertia device: the Orion Ethernet Router.

Orion has a Zoul (CC2538 + CC1200) plus an ENC28J60 ethernet module and support for Active POE (Power Over Ethernet).

For more information please refer to:

* [Orion Product page](http://zolertia.io/product/hardware/orion-router)
* [Orion technical information](https://github.com/Zolertia/Resources/tree/master/Orion%20Ethernet%20Router/Hardware/Revision%20A)

### CODE REVIEW

**Comment by adamdunkels** [comment]
Great! Look like it has IP64 support from the start, right?

:+1: from me!

**Comment by alignan** [comment]
Yes! that's the main feature, it is able to "talk" directly to IPv4-based services :smile:

**Comment by alignan** [comment]
image

**Comment by g-oikonomou** [comment]
👍 tested. This is sweet

**Pull request merged**
