### PR TITLE
Wismote : Direct memory access using UART.

### PR DESCRIPTION
**Pull request by sumanpanchal**

### CODE REVIEW

**Comment by simonduq** [comment]
great!
maybe this should be disabled by default (for now), like on the z1?

**Comment by sumanpanchal** [comment]
@simonduq 
Thanks. I have disabled the DMA for Wismote as like Z1.

**Comment by simonduq** [comment]
oh right, that was in the `contiki-conf.h`
:+1:

**Comment by nvt** [comment]
:+1:

**Pull request merged**
