### PR TITLE
Cc2650 ble stack

### PR DESCRIPTION
**Pull request by Cyfell**
Hi all,
I'm proposing a Bluetooth Low Energy stack for Contiki and CC2650.
I started with Spoerk's pull request (c2f8b58) for implementing ATT protocol and GATT over it.
ATT protocol is not fully implemented but the main functionalities are here.
I have tested with gatttool from BlueZ and it works very well. I can access all sensors values and getting update notifications.
I have also tested with a nexus phone (Android 4.4) and "nordic nrf connect" application. For a good running of the application,  I had to disable two sensors among temp, humidity and pressure.
Part of the stack is under core/ but is not cpu dependant for now because the sensor API is sensor dependant...

ATT functionalities implemented are : 
- ATT_ERROR_RESPONSE is used to state that a given request cannot be performed, and to provide the reason.
- ATT_MTU_RESPONSE is sent in reply to a received Exchange MTU Request.
- ATT_INFORMATION_RESPONSE contains the correlation between handles and uuids.
- ATT_READ_BY_TYPE_RESPONSE contains multiple attributes values.
- ATT_READ_RESPONSE contains the value of one attribute.
- ATT_READ_BY_GROUP_TYPE_RESPONSE contains multiple attributes values and the end of the current group.
- ATT_WRITE_RESPONSE used as acknowledgement of  ATT_WRITE_REQUEST, in order to modificate one attribute value.
- ATT_HANDLE_VALUE_INDICATION contains a value notification of one attribute.

GATT profile is as follow : 
- Generic access (contains device name)
- Information service (contains Contiki version)
- Battery service
- Environmental sensors (contains Temperature, Humidity and Barometer sensors)
- Luxometer sensor
- MPU sensor
- LED control
- Buttons sensors
- Reed relay sensor

This GATT organisation is modular so you can remove sensors expositions like you want.

Thank you for looking at it. I stay open for any comment or way of improvements.
Arthur

### CODE REVIEW

**Comment by Tidone** [comment]
Hello,

first of all, thank you for your ble stack.

Unfortunately we can't get it to work on our devices.
I used the current contiki main-branch and your pr, together with a sensortag and a launchpad.

I also used the nordic nrf app to read the sensor values (Android 7.1.2) and tried to disable the sensors one by one.

The app can connect to the sensortag, but when it tries to discover the services, nothing happens anymore.
To get some output I enabled the debugging outputs in rf-core.c, ble-mode.c, ble-hal-cc26xx.c and rf-ble-cmd.c

Relevant output:
```
command status: 0x0001; connection event counter: 0
command_status_flags: crc_err: 0, ignored: 0, md: 0, ack: 0
rf_ble_cmd_send() could not send cmd
CMDSTA: SCHEDULING_ERR
Status: IDLE
connection error; event counter: 1
Slave command
command status: 0x1401; connection event counter: 1
command_status_flags: crc_err: 0, ignored: 0, md: 0, ack: 0
Slave command
Data type : 0
received control LL
feature request
Slave command
Slave command
Data type : 0
received control LL
Version ind
Slave command
Slave command
Data type : 0
received control LL
parse_ll_ctrl_msg() opcode: 0x00 received
Slave command
Data type : 0
received DATA LL
GET GROUP
ble-mode send() 18 bytes
Slave command
Slave command
Data type : 0
received DATA LL
GET GROUP
ble-mode send() 18 bytes
Slave command
Slave command
Data type : 0
received DATA LL
GET GROUP
ble-mode send() 12 bytes
Slave command
Slave command
Data type : 0
received DATA LL
GET GROUP
ble-mode send() 9 bytes
command status: 0x1401; connection event counter: 15
command_status_flags: crc_err: 0, ignored: 0, md: 0, ack: 1
Slave command
```
After that the last three lines are repeated hundreds of times and the event counter is incremented each time.

Can you help us getting yout pull request to work?

I attached the full log in case you need it.

[output_2017-06-28_10-05-23.zip](https://github.com/contiki-os/contiki/files/1108008/output_2017-06-28_10-05-23.zip)

**Comment by Cyfell** [comment]
Hi Tidone, every thing works well on my side, can you enable logs on ble-att.c, gatt.c, ble-mac.c and give me the result ? Also can you try with BlueZ stack ?

**Comment by Tidone** [comment]
Here is the output with logs enabled.

[output_2017-06-30_11-50-47.zip](https://github.com/contiki-os/contiki/files/1114755/output_2017-06-30_11-50-47.zip)

Unfortunately we don't have a PC, laptop, or bluetooth stick, which support BLE, so we can't test with BlueZ.

In the meantime I tested your example with a different phone with Android 6, but the error stays the same.

Are you also using the latest contiki main branch? If not, can you try your pull request with vanilla contiki?

**Comment by Cyfell** [comment]
I cleaned all and started from fresh contiki + PR and it works... If you have you wifi on, it can interfering with BLE on the phone, I think you have a lot of 
`command status: 0x1401; connection event counter: 19
command_status_flags: crc_err: 0, ignored: 0, md: 0, ack: 1` 
becouse of that, try without. And disable all sensors in gatt_config (there will always be two generic GATT attributes to show on nordic app)

**Comment by Tidone** [comment]
Thank you, I will try again on monday and keep you updated.

**Comment by Tidone** [comment]
Still no luck.
This time I turned off Wifi and our 6lowpan-router, but the result is still the same.

I uploaded the binary for the sensortag. Can you test it on your hardware to rule out software/compiler bugs?

Can you also upload a working version so I can test it on my hardware?

[ble-gatt-demo.zip](https://github.com/contiki-os/contiki/files/1118725/ble-gatt-demo.zip)

**Comment by Cyfell** [comment]
it works well on my side with your bin file...(it's quite frustrating xD)
here is mine : 
[ble-gatt-demo.zip](https://github.com/contiki-os/contiki/files/1121485/ble-gatt-demo.zip)
maybe its an android problem, or my stack has a problem not handled with my android version but corrected with yours.... I dont have an other phone for testing...

**Comment by Cyfell** [comment]
ok i found an android 7.X phone and effectively it does the same as you... 0x1401 means that the reply from the phone doesn't come back in the time window defined in the sensortag (or doesn't come back at all).
you can found more info maybe here http://www.ti.com/lit/ug/swcu117g/swcu117g.pdf page 1661
a bit of this error is not dramatic but in this case it prevent the phone to communicate with the Sensortag.
at first I think the error come from rf-ble-cmd.c...
I'm not very available this week to investigate this problem...

**Comment by tonnenpinguin** [comment]
Hi @Cyfell!
Did you get a chance to look into this issue?
Is there any way one can help to move this forward?

**Comment by Cyfell** [comment]
It will be back...

**Pull request closed without merging**
