### PR TITLE
sensors: bme280 weather sensor

### PR DESCRIPTION
**Pull request by alignan**
This PR sits on top of https://github.com/contiki-os/contiki/pull/1863 and includes small architecture fixes, and a patch submitted by @herjulf

### CODE REVIEW

**Comment by herjulf** [comment]
Thanks a lot for fixing and making the PR much more generic with the arch I2C design. This PR passed my platform test but there seems to some fail for regression error.

**Comment by alignan** [comment]
It is not related to the PR, but to Travis failing to set up th Nordic environment, I just restarted the job.

**Comment by herjulf** [comment]
Right. It passed.

**Comment by alignan** [comment]
:+1: 

Setting a timeout to merge, but another thumbs-up is welcome to have this sooner

**Comment by herjulf** [comment]
Thanks! Happy to see this improved and finalized.
Cool.

**Pull request merged**
