### PR TITLE
update uart1.c to include Special function registers bits definitions

### PR DESCRIPTION
**Pull request by MohamedSeliem**
including "sfr-bits.h" to define PERCFG_U1CFG, and UCSR_MODE.

### CODE REVIEW

**Comment by MohamedSeliem** [comment]
@simonduq any feedback on this
Thanks

**Comment by simonduq** [comment]
can you explain why this is needed?

**Comment by g-oikonomou** [comment]
I'll have a look at this one. Self-assigning

**Comment by MohamedSeliem** [comment]
if you tried to use the uart1 of a cc2530, you will find 2 errors at compilation.
../../../cpu/cc253x/dev/uart1.c:34: error 20: Undefined identifier 'PERCFG_U1CFG'
../../../cpu/cc253x/dev/uart1.c:57: error 20: Undefined identifier 'UCSR_MODE'

because PERCFG_U1CFG, and UCSR_MODE are used without being defined.

 PERCFG_U1CFG,  UCSR_MODE  are defined in the sfr-bits.h and used in configuring uart0.c

**Pull request merged**
