### PR TITLE
Modify obsolete  macro related to neighbor cache table size

### PR DESCRIPTION
**Pull request by MohamedSeliem**
UIP_CONF_DS6_NBR_NBU, the number of elements in neighbor cache requested by the user in contiki configuration, is obsolete.
NBR_TABLE_CONF_MAX_NEIGHBOR is the latest Macro which is related to neighbor cache table

### CODE REVIEW

**Comment by MohamedSeliem** [comment]
This simple fix, set the maximum number of neighbor entries  in the neighbor table as defined in the project configuration file for (ipv6/ multicast example)
and without this fix, the defined value of the neighbor entries  in the neighbor table will be set to the default value as defined in (ipv6/ nbr-table.h)

**Comment by MohamedSeliem** [comment]
@g-oikonomou  can i got your feed back on this.

**Comment by g-oikonomou** [comment]
You are right, those are the old defines. You probably want to be using
`NBR_TABLE_CONF_MAX_NEIGHBORS` and `UIP_CONF_MAX_ROUTES`

**Comment by MohamedSeliem** [comment]
great.
I do not think we have a problem in case of (UIP_CONF_DS6_ROUTE_NBU), as routing table defined it

/* Routing table */
#ifndef UIP_CONF_MAX_ROUTES
#ifdef UIP_CONF_DS6_ROUTE_NBU
#define UIP_DS6_ROUTE_NB UIP_CONF_DS6_ROUTE_NBU
#else /* UIP_CONF_DS6_ROUTE_NBU */
#define UIP_DS6_ROUTE_NB 4
#endif /* UIP_CONF_DS6_ROUTE_NBU */
#else /* UIP_CONF_MAX_ROUTES */
#define UIP_DS6_ROUTE_NB UIP_CONF_MAX_ROUTES
#endif /* UIP_CONF_MAX_ROUTES */

even though, updating to recent macros is a good way to move forward.

P.s. I redefined the Macros of nbr table, to avoid such a problem (a hidden, or unwilling used (UIP_CONF_DS6_NBR_NBU) ).

**Comment by MohamedSeliem** [comment]
@g-oikonomou any progress here?

**Comment by simonduq** [comment]
I would rather fully retire the two old macros, by:
1) reverting the change to `nbr-table.h`
2) removing all definitions of `UIP_CONF_DS6_NBR_NBU` and `UIP_CONF_DS6_ROUTE_NBU` (not only in the multicast example)

**Comment by simonduq** [comment]
now replaced with https://github.com/contiki-os/contiki/pull/1849

**Pull request closed without merging**
