### PR TITLE
Fixing Cooja message list to avoid any Swing components when headless

### PR DESCRIPTION
**Pull request by joakimeriksson**
This fix make Cooja not use the MessageList class that do have a lot of Swing components that now and then cause sporadic exceptions when running in headless mode. This introduce a text-based version that just prints the messages on standard out - the Text based MessageList is used whenever Cooja is run in headless mode.

### CODE REVIEW

**Comment by simonduq** [comment]
Well all I can say is that this is the first PR I see succeeding on the ipv6 test for the first time since we switched to single-seed Travis tests.
Re-started the test it to see if we get the same result again :)

**Comment by joakimeriksson** [comment]
Sounds good! I think Cooja in general needs to be more headless when it is run in headless. It is quite a risk to create lots of Swing / AWT components when not having a GUI.

**Comment by pablocorbalan** [comment]
This PR includes in the first commit your previous PR [1633](https://github.com/contiki-os/contiki/pull/1633). It would be good if you can separate them.

**Comment by joakimeriksson** [comment]
@pablocorbalan good catch - my bad - fixed now!

**Comment by fros4943** [comment]
Look great @joakimeriksson! 

:+1: Merging

**Pull request merged**
