### PR TITLE
Test cc2538dk with the recommended toolchain

### PR DESCRIPTION
**Pull request by g-oikonomou**
As per the subject, the objective of this pull is to test cc2538dk with the toolchain recommended in the platform's README (GNU Tools for ARM Embedded Processors), instead of the one that was being used two years ago (Sourcery G++ Lite 2008q3-66). The job using the former is currently disabled on Travis, due to being broken for the ev-aducrf101mkxz platform.

With this in mind, this pull:
* Moves cc2538dk tests to the arm-aapcs job, which is the one using GNU Tools for ARM Embedded Processors
* ~~Re-enables the job in `.travis.yml` and~~~ changes `BUILD_ARCH` from 'arm'  to 'arm-aapcs' for clarity
* ~~ev-aducrf101mkxz tests remain disabled, but this is now done within the job's Makefile rather than in `.travis.yml`. Re-enabling tests for this platform will be a trivial patch.~~

And a quick ping @jimparis for ideas on how to restore ev-aducrf101mkxz tests

### CODE REVIEW

**Comment by jimparis** [comment]
It looks like the only thing that changed between a successful build ([2044.16](https://travis-ci.org/contiki-os/contiki/jobs/43447748)) and a failing build ([2055.16](https://travis-ci.org/contiki-os/contiki/jobs/43613252)) is that the GCC toolchain version changed from `4.8.4.2014q3-0precise11` to `4.9.3.2014q4-0precise12`.  Will look into it further.

**Comment by jimparis** [comment]
Need to use [gcc-ar and gcc-nm](https://gcc.gnu.org/wiki/LinkTimeOptimizationFAQ?action=recall&rev=5#ar.2C_nm_and_ranlib).  I'll submit a new pull request.

**Comment by jimparis** [comment]
Submitted as #963

**Comment by g-oikonomou** [comment]
Rebased this on top of #963

**Comment by g-oikonomou** [comment]
Simplified and rebased on top of 9fcb7f7

**Comment by g-oikonomou** [comment]
@bthebaudeau @uknoblic @areaarea @hexluthor how do you feel about this?

**Comment by areaarea** [comment]
Fine as well. Let's clear some of the back log. 😊

**Pull request merged**
