### PR TITLE
Minor changes to z1/contiki-conf.h

### PR DESCRIPTION
**Pull request by alignan**
Minor changes:

* Moved `project-conf.h` inclusion to the top of `contiki-conf.h`, as configurable parameters are defined beforehand, thus requiring to `#undef` first.
* Made common parameters overridable
* Added `BOARD_STRING` platform definition

### CODE REVIEW

**Comment by alignan** [comment]
:+1:

**Comment by simonduq** [comment]
I think this might cause problems with all `project-conf.h` files that assume they are included after this `contiki-conf.h`, as the latter sometimes sets some flags without `ifndef`. I feel we need to agree on a config architecture and stick to it in all examples and platforms, else this soon getting messy.

**Comment by alignan** [comment]
Agree, I changed this to follow how the `RE-Mote` and newer platforms like the `srf06-cc26xx`, as I think it is better implemented (it is ugly to #undef a `CONF_XXX` value from a `project-conf.h`).  

At the moment at least it should be easy to spot as it will yield a lot of warnings :smile:

**Comment by simonduq** [comment]
Yes true, at least easy to spot :)

**Pull request merged**
